### ISSUE TITLE
App crashes when syncing to the Kolab server

### ISSUE THREAD

**Issue by lhitc** [konradrenner/kolabnotes-android#1]
After adding my Kolab server account (pretty much default Kolab 3.3 installation from official Kolab repositories) the app crashes and syncing of the account is turned off.
When I turn on sync, it crashes again, but this time sync remains active. However, no notes from the Kolab server show up in the app.
This is 100% reproducible.

However I'm not quite sure what to enter as the "IMAP root folder". I tried "/" as well as "/Notes" and even "Notes". Maybe this is the source of the issue.
Still I would expect to get a message instead of a crash (at least at a later release stage ;-)

Android 5.1 @ LG Nexus 5

**Comment by lhitc** [comment]
Possibly I missed something when putting the app together in Android Studio?

**Comment by konradrenner** [comment]
Do you use a different port than 993? Do you use SSL or not?
Try to fill in the properties like this:
Account name: "What ever you want"
IMAP server url (the same url which is used by mail clients for mail syncing): imap.kolabserver.com
IMAP root folder (as you may know, you can have different folders which contain notes): Notes
Email: max.mustermann@kolabserver.com

Do you have 2 account entries in the navigation drawer? Did you select the "Notes from all accounts" option in the navigation drawer (this should bring you all your notes)? Notebooks are not loaded until you selected a note and then switched back to main activity (I know this is a bug ;-) )

**Comment by lhitc** [comment]
I used the correct server URL (in my case mail.myserver.xyz) and tried port 993 with SSL/TLS as well as 143 with STARTTLS. I'm pretty sure I used the correct account credentials and I tried "Notes" and "/Notes".
Via Thundebird I see the IMAP folder "Notes" and the contained notes in both of the above IMAP configurations.
Tried it all again some minutes ago to make sure ;-)

The server uses a self signed certificate, if that might be an issue.

I see 2 account entries, the local one and the one I added. I only see the local notes no matter if I select "Notes from all accounts" or select local account and "Notes from selected account".
I don't see anything from the Kolab server. Following the workaround procedure (opening a note) doesn't help either.

Since I still think it might be a build time issue it would be great if you could provide a working apk for me to check ;-)

**Comment by konradrenner** [comment]
Hmmm this is very strange. I don't think this is a build time issue, I think it is a bug in the app ;-), so I have to check the code

**Comment by konradrenner** [comment]
should be fixed in current master. i tested syncing via with KolabNow, with GMAIL and GMX. Connecting and downloading notes from each provider worked

**Comment by lhitc** [comment]
No improvement on that for me, using the APK-Tarball released 2015-05-14.
I tried the following configurations:
Port 993, SSL enabled
Port 143, SSL enabled
Port 143, SSL disabled

As stated before, all of these configurations work when accessing the Kolab server with Thunderbird via IMAP. I see the "Notes" folder in Thunderbird, the notes contained there and for every note the kolab.xml which I can open and read as XML.
The server uses a self signed certificate.

When accessing via port 993 the server's mail.log shows:

xxxxx imaps[9666]: imaps TLS negotiation failed: my.dynamic.hostname.de [aa.bb.cc.dd]
xxxxx imaps[9666]: Fatal error: tls_start_servertls() failed
xxxxx master[1873]: process type:SERVICE name:imaps path:/usr/lib/cyrus-imapd/imapd age:26.910s pid:9666 exited, status 75

When using port 143, there are no log entries.

**Comment by lhitc** [comment]
No change with today's second preview

**Comment by lhitc** [comment]
After further tests, this is probably an issue with self signed certificates.

A solution may be found here:
http://stackoverflow.com/questions/4894954/how-to-ignore-server-cert-error-in-javamail

While the main Stackoverflow solution is the easy way, it might be better to ask the user for acceptance of the certificate, as also mentioned in a comment at Stackoverflow.

**Comment by konradrenner** [comment]
This should now be fixed, please test it and reopen the issue, if it is not fixed. At the moment the solution from Stackoverflow is used, I will create an own issue for correct certificate handling

**Comment by lhitc** [comment]
Works!

**Comment by laclaro** [comment]
Hi,

with the most recent version from F-Droid I still get the same errors 

```
imaps[000]: imaps TLS negotiation failed: [xx.xx.xx.xx]
imaps[000]: Fatal error: tls_start_servertls() failed
```

My cyrus 2.5 is configured to enable SSL on port 993 but I'm wondering whether STARTLS is allowed. Hovever, I want to stick to SSL/993. How do I make it work?

The error indicates that the connection establishment fails. I found only one very old post about this: https://lists.andrew.cmu.edu/pipermail/info-cyrus/2010-January/032393.html

I use an SSL certificate from let's encrypt. May I check and trust it somehow?

Best regards,

Henning

**Comment by konradrenner** [comment]
Does it work with port 143?
