### ISSUE TITLE
FolderNotFoundException: Configuration not found

### ISSUE THREAD

**Issue by rwrnet** [konradrenner/kolabnotes-android#104]
When I try to sync an IMAP account with KobalNotes it fails due to trying to find and create a folder "Configuration" without considering Prefix of the Imap account.

```
  A4 CREATE Configuration..
  A4 NO Invalid mailbox name...

  A5 SELECT Configuration..
  A5 NO Mailbox does not exist, or must be subscribed to...

  A6 LIST "" Configuration..
  A6 OK LIST completed..
```

From the configuration "Imap Rootfolder", I would have expected, that its just the prefix for the account. So in my case (or any other Courier based Imap setup), this would have been INBOX. As it turns out, the root folder is meant to be the Notes folder, I can see Kolabnotes properly synching the folder, but then failing with before mentioned error message, which does not respect the root folder setting at all.

**Comment by konradrenner** [comment]
If you want to use KolabNotes with a "plain" IMAP server (no Kolab extensions active) you have to create an IMAP folder on your server where you want to store your notes (e.g. a folder with the name "Notes") this folder you have to provide in the "root folder" field. So if there is no folder with the name "Notes" of the name you specified in the "root folder" field the sync will fail. However, it is not possible to sync your notes with your INBOX.

@rwrnet does this information help you, with the creation of a sync account on your device?

**Comment by rwrnet** [comment]
Have a look on my log output. I have properly created the Notes folder under the mandatory Courier prefix INBOX. So INBOX.Notes exists and I added it as root folder. In the logs I can see, this is used correctly by KolabNotes, but in addition it is trying to access and create a folder **Configuration** which fails and due to couriers mandatory Prefix cannot be fixed, as there is no option to change the Configuration folder name or set a prefix like "INBOX" for this operation.

**Comment by konradrenner** [comment]
The folder Configuration is needed for storing tags. Is it possible for you to create a folder INBOX.Configuration ? Maybe this solves the problem.

**Comment by rwrnet** [comment]
As KolabNotes was trying to create the folder without Prefix, I did not try to create the Folder with Prefix manually. But actually, that helped. Thanks Konrad.

I now found out that Kollabnotes isn't able to handle IOS Notes Format and get tons of "NOT_LOADED" Notes, but this is a different Story.

**Comment by konradrenner** [comment]
@rwrnet if you can send me a specification of the IOS notes format, maybe we will be able to create an import routine

**Comment by rwrnet** [comment]
Thanks Konrad,
I doubt the format specification is open, but its basically html consisting of `<div>`s and `<br>`s. I'll open an issue with an example tonight.
Best, 
Rene
