### ISSUE TITLE
Make richtext optional 

### ISSUE THREAD

**Issue by PulsarFX** [konradrenner/kolabnotes-android#105]
Loading up the richtext editor takes some time and adds lots of stuff to the window. I'd prefer plain text notes for better performance and less complex ui.

**Comment by proninyaroslav** [comment]
I think that proprietary formats are not the best choice. The best choice - markdown.

**Comment by konradrenner** [comment]
at them moment the richtext editor produces text which is formatted with html tags.

@maulwuff @proninyaroslav what do you think of the following approach:
In the general settings, there is a dropdown where the user can select which type of text editor he wants to use globally for the app (Richtext, Markdown, Plain). In the DetailFragment, the choosen editor will be shown.
But the user must be warned, if he chooses something other than Richtext (Richtext should also be the default). Because I think the web UI of a Kolab server doesn't support Markdown and if the user choose Plain, synced formatted text will not be displayed correct.

**Comment by proninyaroslav** [comment]
Markdown could be used for local notes, and could be converted into rtf or html for Kolab server (if user wants to use synchronization).

**Comment by PulsarFX** [comment]
You mean a global default format and the possibility to change the format on each note? Sounds good.

**Comment by konradrenner** [comment]
@maulwuff I am thinking of a configuration option which will let you choose which type of editor will be started when you open a note detail

**Comment by proninyaroslav** [comment]
@maulwuff Yes, that's what I mean.
@konradrenner I think this would complicate the application. In terms of use.

**Comment by konradrenner** [comment]
@proninyaroslav @maulwuff I think markdown is hard to use for an average user. I think the best way would be to give the user a gloabl config option where he can choose, if he wants to use markdown, html or plan text.

But the next problem will be, if one syncs with a Kolab server, how to convert a html note (Kolab web ui saves notes as html notes) to markdown...

Maybe it would be better, if one can specify the used editor per account, but I think this will complicate the app and a user will be confused if he has different editors.

Do you have any idea how it could work?

**Comment by proninyaroslav** [comment]
I had the idea to make a single editor markdown.
1) data is stored in html 
2) during editing html converted into markdown (I think it is much faster than WebView) 
3) after editing the data is saved in html

**Comment by konradrenner** [comment]
hmm, but don't you think markdown is too complicated for an average user? An user which don't has any programming skills...

**Comment by proninyaroslav** [comment]
You can see an example markdown editor for comments on GitHub. Find or make editor in java no problem.

**Comment by PulsarFX** [comment]
I'd stay with HTML and plaintext as this can be easily put in a HTML structure after editing. 

If you want to do editing with an editor it is not relevant whether it is formatted as markdown or HTML. My aim was to get completely rid of any additional editor.

**Comment by proninyaroslav** [comment]
I'm embarrassed by bad performance webview, the big note, the slower rendering. I will look for ways to solve this problem.

**Comment by konradrenner** [comment]
I have reflected this issue many times now, and issue #113 is similar to this one. I think providing a global option, where the user can decide which type of editor he wants to use, is the best way. The Android default text input also accepts html formatted text.

I will implement the config option, where the user can choose between richtext and Android default. @proninyaroslav  if you want, you can add an option markdown, if the markdown editor can parse html formatted text und produce html formatted text

**Comment by konradrenner** [comment]
is done @proninyaroslav you are free to add markdown support ;-) to one of the editors

**Comment by proninyaroslav** [comment]
> is done @proninyaroslav you are free to add markdown support ;-) to one of the editors

Ok.
