### ISSUE TITLE
Support IOS Notes Format

### ISSUE THREAD

**Issue by rwrnet** [konradrenner/kolabnotes-android#106]
In order to share Notes between IOS Devices Notes App and Android KolabNotes devices, the format should be supported by KolabNotes as far as easily possible. A quick web research did not discover an open available specification, but from the source code of a formatted note, it looks pretty simple, so maybe even an example is enough to include support.

This is an example, stored with an Iphone 4s on IOS 9.0.2

```
Content-Type: text/html;
    charset=utf-8
Content-Transfer-Encoding: 7bit
Subject: Format IOS Notes
From: =?utf-8?Q?....?= <...@...>
X-Universally-Unique-Identifier: 71514EF8-64F2-4FE2-A9BC-0E2A41B90E4B
X-Uniform-Type-Identifier: com.apple.mail-note
Message-Id: <8D7FF269-815B-4F85-81D5-6835CFE84F01@...>
Date: Tue, 26 Jan 2016 18:42:17 +0100
X-Mail-Created-Date: Tue, 26 Jan 2016 18:38:39 +0100
Mime-Version: 1.0 (iOS/9.0.2 \(13A452\) dataaccessd/1.0)

Format IOS Notes<div>For KolabNotes an example. With some</div><div><br></div><div>Linefeeds</div><div><br></div><div>and <b>bold</b> <i>italic</i> <u>underlined</u> <b><i><u>formatting</u></i></b>.&nbsp;</div><div><br></div>
```

IOS Notes App takes the first line in the note as subject of it.

If I can support in any way, just let me know.

**Comment by konradrenner** [comment]
do you want that the sync gets extended, or would it be ok to create an import option?

**Comment by rwrnet** [comment]
Could you elaborate a bit more about these options. Is import a kind of "one of" option, which modifies all existing notes to Kolabformat, and "extended sync" would try to translate between both worlds?

If yes, the latter would be preferred, as some notes contributors are reluctant to switch to android. ;)

However I could imagine, that it doesn't sound right for a Kolab specific app, to try to translate iOS Stuff, but I also have the impression, that KolabNotes tries to be more of a Notes Swiss Army Knife with some loosely coupled relation to Kolab.

**Comment by konradrenner** [comment]
For the Kolab Notes app I could imagine an import option, but the app is coupled to the Kolab storage format. 

But I think creating an oss multipurpose notes app for android would be really cool (which can sync with Kolab, IMAP, IOS Notes, Evernote, etc.). There was some discussion already in a GitHub repo about this topic: https://github.com/plafue/writeily-pro/issues/159

Maybe you can add this requirement to this issue and coordinate the development of such an app ;-)

For the mean time, I will add the import/export possibilty of IOS notes, to the already existing Import/Export issue
