### ISSUE TITLE
Start up crashes

### ISSUE THREAD

**Issue by guilhas** [konradrenner/kolabnotes-android#108]
Hello,

I had some notes on the app, and when pasting a image to a new note the application crashed. Now every time I try to start it says 'Unfortunately, Kolab Notes has stopped'

How could I access the text/db/xml file storage to retrieve notes?
So then  I can safely try 'Clear data' in 'App Info' and start the app again.

If this should be asked somewhere else please say.

No sync was active just local
Kolab 1.4/5.x later updated to Kolab 1.6.0

Thank you,

**Comment by konradrenner** [comment]
Hi,

did you report the crash on Google Play via the Android crash system?
On the Android settings, choose Apps, search the App and there you have a delete data button.

Please let me know if this helps you. What type of image did you add to the note?

Yours, Konrad

**Comment by konradrenner** [comment]
Please provide a stacktrace or some error informations, an reopen the issue, if the error still occurs
