### ISSUE TITLE
Include a Changelog Link, within the F-Droid App', on Info' Page; 1.7.1.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [konradrenner/kolabnotes-android#110]
Include a Changelog Link, within the F-Droid App', on Info' Page.  Not present, as of: 1.7.1.

**Comment by konradrenner** [comment]
How can I do that?

**Comment by locutis-of-borg-1999** [comment]
https://f-droid.org/manual/html_node/Changelog.html#Changelog

**Comment by konradrenner** [comment]
And how can I change the URL for the changelog? There is no description, do I have to open an issue for the F-Droid guys?

**Comment by locutis-of-borg-1999** [comment]
I've been busy.  Yes if you give them your link, it happens rather quickly.

https://f-droid.org/wiki/page/org.kore.kolabnotes.android

**Comment by konradrenner** [comment]
created an issue for the F-Droid guys: https://gitlab.com/fdroid/fdroidserver/issues/162
