### ISSUE TITLE
Unsaved changes are lost when the screen rotates.

### ISSUE THREAD

**Issue by AbortRetryFail** [konradrenner/kolabnotes-android#111]
Unsaved changes to a note are lost without prompting when the device's screen changes from portrait to landscape or vice versa.

This happens whether Auto-Rotate is enabled or prompted by hardware such as a slide-out keyboard or docking station.

**Comment by proninyaroslav** [comment]
Fixing soon.

**Comment by konradrenner** [comment]
@proninyaroslav :+1: !

**Comment by proninyaroslav** [comment]
I think close issue. 
@konradrenner please check patch and make release.

**Comment by konradrenner** [comment]
Release is in the way!

**Comment by AbortRetryFail** [comment]
Works as expected now on 1.7.2. Thanks! :+1:
