### ISSUE TITLE
make richtext editor slightly more intelligent (formatting of urls)

### ISSUE THREAD

**Issue by mhellwig** [konradrenner/kolabnotes-android#113]
a double-edged sword since the editor is catastrophically slow as it is .. 
BUT
very often I will generate a note by using "share <whatever>" from inside another app. So a bunch of text will be dumped into the note. If there is a url in that bunch of text somewhere, there is no straightforward way to turn that url into a url-element. Ideally, the editor would recognize urls as urls and mark them thusly by itself.

Note: it would be even better if the editor could be replaced by a plain-text editor that still recognizes urls as urls and makes them clickable. A man can dream.

**Comment by konradrenner** [comment]
I think this issues is targeting the same goal as issue #105
