### ISSUE TITLE
Printing of notes

### ISSUE THREAD

**Issue by konradrenner** [konradrenner/kolabnotes-android#115]
Support printing of notes, as entry for this topic look here: 

http://developer.android.com/about/versions/android-4.4.html#Printing

http://developer.android.com/reference/android/print/package-summary.html

**Comment by konradrenner** [comment]
http://developer.android.com/training/printing/custom-docs.html

**Comment by proninyaroslav** [comment]
Why not http://developer.android.com/intl/ru/training/printing/html-docs.html ?

**Comment by konradrenner** [comment]
Great! Did not discover this one ;-), do you want to implement this issue?

**Comment by proninyaroslav** [comment]
Yes. If not today, then a few days.

**Comment by konradrenner** [comment]
Great!!! I think printing support is an important feature for a note taking app. Thanks for your help!

**Comment by konradrenner** [comment]
new release with print support is on the way ;-)
