### ISSUE TITLE
Full attachment support

### ISSUE THREAD

**Issue by konradrenner** [konradrenner/kolabnotes-android#118]
Create a possibility to add/remove attachments to a note.
There schould be an attachment dialog/fragment/activity which can be launched from a note detail. there should be a list of attachments. It should be possible to open attachments from this view, create new ones and delete uneeded.

**Comment by konradrenner** [comment]
For sync support this issue has to be done first: https://github.com/konradrenner/kolabnotes-java/issues/6

**Comment by konradrenner** [comment]
kolabnotes-java starting with 3.3.0 has full attachment support :-)

**Comment by greve** [comment]
You guys rock!

**Comment by konradrenner** [comment]
@greve Thank you!

**Comment by konradrenner** [comment]
could be useful for displaying the list of attachments on tablets:

http://developer.android.com/guide/topics/ui/dialogs.html#ActivityAsDialog

**Comment by konradrenner** [comment]
Done with next release
