### ISSUE TITLE
Large memory leak

### ISSUE THREAD

**Issue by proninyaroslav** [konradrenner/kolabnotes-android#119]
Memory monitor in Android Studio shows that at every rotate memory leak increases by 10-15 Mb. Leak does not depend on whether I am on the main activity or the detail activity. I compared with many applications and the result kolab notes was the highest.

![1](https://cloud.githubusercontent.com/assets/7840559/13995677/97953fcc-f143-11e5-9e4e-db14d01226d4.png)

**Comment by konradrenner** [comment]
Does it mean, that the memory consumption of the app increases permanently with every rotate?

**Comment by proninyaroslav** [comment]
@konradrenner exactly.

**Comment by proninyaroslav** [comment]
I make memory usage dump https://www.libresoft.ml/ftp/org.kore.kolabnotes.android_converted.hprof
It can be viewed using Eclipse MAT.

**Comment by proninyaroslav** [comment]
Dump analysis showed that the blame for the leaks memory package **com.mikepenz.materialdrawer.accountswitcher**

![1](https://cloud.githubusercontent.com/assets/7840559/14464470/f7245c1a-00df-11e6-8e17-0348579e61ef.png) ![3](https://cloud.githubusercontent.com/assets/7840559/14464471/f746eba4-00df-11e6-84d9-d4872321285b.png) ![4](https://cloud.githubusercontent.com/assets/7840559/14464472/f7710c04-00df-11e6-9cf3-59b32207407f.png)

**Comment by konradrenner** [comment]
bad news... I already tried to update the switcher, but there are 2 problems:
1) API breaks completely
2) After handling rewriting the code so that the app compiles, the app does not start or the drawer does not work as expected

I think we should write our own drawer for the app from scratch, so that we have any changes in our hands. @proninyaroslav what do you think?

**Comment by proninyaroslav** [comment]
I think should use DrawerLayout from the standard lib. He will give the same result as the present library.

**Comment by konradrenner** [comment]
Do you have any experience with the DrawerLayout?

**Comment by proninyaroslav** [comment]
Yes, but now I'm busy, and will try to help in parallel with DrawerLayout.

**Comment by konradrenner** [comment]
Ok, no problem. I think this change will be massive

**Comment by konradrenner** [comment]
will be fixed in 3.0.0
