### ISSUE TITLE
Select text with double-click while in Rich text mode?

### ISSUE THREAD

**Issue by ghost** [konradrenner/kolabnotes-android#126]
I can only seem to select text by double-clicking it when i have rich text disabled. Is this a coding limitation or is it possible to allow text selection _and_ rich text? Thank you.

**Comment by konradrenner** [comment]
Hi, what Android version do you use? Because on my Android 5.1 device I can select text with a long touch on a word or with a double tap. Long touch also works if rich text is disabled.

Can you please provide an example how the expected behaviour is?

**Comment by ghost** [comment]
I use CyanogenMod 13 which is Android 6.0 based. As long as rich text is turned off, double-clicking selects words, but with rich text enabled, double-clicking does nothing, and neither does long touch.

I currently use Tomdroid for my notes, but i'm looking for an alternative since it has bugs and is no longer updated. Selecting text by double-clicking with (a somewhat limited) rich text works fine in Tomdroid. This is what i'd like to see.

Also, a separate issue: Kolab Notes crashes for me when quitting from an empty note. I click on the New note icon, type nothing and press back instead and it says Kolab Notes has stopped.

Addition to the above: It crashes when i have  Rich Text disabled. No crash if it is enabled. Maybe it's related after all?

**Comment by konradrenner** [comment]
Ok thanks, the crash will be a bug and I will create a new issue to track it.

On the Android 6 based emulators I use for app development selection is also possible, I will test it on a real device with stock Android 6 and post the result as comment here.

**Comment by ghost** [comment]
I examined it a bit more, and the note headline is not rich-text supported, is it? I do not see the rich text bar when typing a note headline, and i **can** select the headline with a double-click. Just not the actual note contents, which are rich-text editable.

**Comment by konradrenner** [comment]
The headline/summary if the note does not support rich text. Rich text is just supported in the note description.

**Comment by konradrenner** [comment]
Which version of the app do you use? Did you get the app via Google Play or F-Droid?

**Comment by ghost** [comment]
Version 2.0.7, updated to F-Droid repos on 3.5.2016.

**Comment by konradrenner** [comment]
I have tested it now on 2 different emulators and 2 different real devices (Nexus 4 - Android 5.1 and Pixel C Android 6.0). I cannot reproduce this problem. Maybe it is a bug of the Richtext editor component which I use on CyanogenMod. So please report a bug here: https://github.com/wasabeef/richeditor-android
