### ISSUE TITLE
How to delete drawings?

### ISSUE THREAD

**Issue by jluttine** [konradrenner/kolabnotes-android#128]
This must be a stupid question but I just couldn't figure out a way to delete a drawing.. How to do it? Also, is it possible to edit existing drawing?

**Comment by konradrenner** [comment]
Hi,
no question is a stupid question ;-). 
Just position the cursor after the drawing and hit the backspace button of your keyboard. Technically there is no difference between a drawing or an embedded image.
Edit of drawings is not supported.

**Comment by konradrenner** [comment]
PS: Please reopen the isssue if the answere didn't help your ;-)

**Comment by jluttine** [comment]
Thanks for the response. Yep, I tried that, but I can't get it working.. I first move to the end with arrow keys or touch, then press backspace so many times that everything is deleted and nothing happens anymore. But the drawings won't disappear. Tried again and again but nope, they just stay there. An embedded image was deleted, but not drawings. I'm using the version from F-droid if that makes any difference. And I can't re-open this issue, only comment button available..

**Comment by konradrenner** [comment]
OK, very strange...
What Android version do you use? Are you using stock Android, a custom rom or a pre installed version from a device manufactor? What version of the app do you use?

**Comment by jluttine** [comment]
Kolab 2.0.8. Cyanogenmod 11-20141115-SNAPSHOT-M12-i9300.

**Comment by jluttine** [comment]
Even Ctrl-A and then Backspace doesn't delete the drawings.

**Comment by konradrenner** [comment]
Is it correct that Cyanogenmod 11 is Android 4.4 based?
On my Android 5 device everything works as expected...

**Comment by jluttine** [comment]
Yep. The exact version on my phone is Android 4.4.4.

**Comment by konradrenner** [comment]
Now I have tested it with an Android 4.4 emulator and everything works as expected. Maybe the Cyanogenmod has an issue?!

I just positioned the cursor after the drawing and hit the backspace and the drawing was deleted...

**Comment by konradrenner** [comment]
I don't think there has to be something done in Kolab notes Android app, because it works on Android 4.4 emulator, Android 5 and 6 emulator and Android 5.1 and 6 real devices

**Comment by jluttine** [comment]
Ok, thanks for testing thorouhly. Did you try F-Droid build? Perhaps the issue is in F-Droid build rather than Cyanogenmod.

**Comment by konradrenner** [comment]
No I don't tried but I cannot change anything in F-Droid build and it does the same as the manual build for Google Play because of the Gradle build System, but maybe you can try and let me know if it makes a difference

**Comment by jluttine** [comment]
Just for information: I tested on normal Android 4.4.4 GT-I9305 with both Google Play and F-Droid versions. Both worked as expected. So the issue is probably related to Cyanogenmod. Thanks for your help!

**Comment by konradrenner** [comment]
Thanks for the informations! I will link this issue with one I think it is related (issue in the Richeditor component). Also there was already an issue with Cyanogenmod and the Richeditor reported here: https://github.com/konradrenner/kolabnotes-android/issues/126

Will Link this issue with this one : https://github.com/wasabeef/richeditor-android/issues/5
