### ISSUE TITLE
Exported notebooks do not include the description

### ISSUE THREAD

**Issue by korelstar** [konradrenner/kolabnotes-android#129]
If I use the export function of kolab notes 2.0.8, the XML files in the resulting ZIP file do not contain
- the description, i.e., the actual note, and
- the assigned categories

Is this intended or a bug?

**Comment by konradrenner** [comment]
Hi, the description of a note should be exported in the description Tag of the xml. If not there is maybe a bug.

Categories are not exported at the moment, this would be a new feature.

Which version of the app and Android do you use? Can you attach a problematic exported note to this issue?

**Comment by korelstar** [comment]
I'm using kolab notes 2.0.8 on Android 6.0. The export function generates the following data:
`<?xml version="1.0" encoding="UTF-8"?><note xmlns="http://kolab.org" version="3.0"><uid>edcbad34-c93e-441a-b154-b0b3f96a46e3</uid><prodid>kolabnotes-java</prodid><creation-date>2016-06-20T13:25:11Z</creation-date><last-modification-date>2016-06-22T11:25:11Z</last-modification-date><classification>PUBLIC</classification><summary>Test</summary><description/><color/></note>`

I've looked at the code and found the following:
- When choosing export from the menu, the `AsyncTask` named `ExportNotebook` from `OverviewFragment` is executed.
- Here, in https://github.com/konradrenner/kolabnotes-android/blob/e8ac5992c78de6bd841986da425be9b500e48ed6/app/src/main/java/org/kore/kolabnotes/android/fragment/OverviewFragment.java#L1403, `NoteRepository.getFromNotebook(...)` is called to get the Notes from the Notebook.
- Then, all columns from the note are loaded: https://github.com/konradrenner/kolabnotes-android/blob/e8ac5992c78de6bd841986da425be9b500e48ed6/app/src/main/java/org/kore/kolabnotes/android/content/NoteRepository.java#L165
- However, `cursorToNoteWithoutDescription(...)` is called: https://github.com/konradrenner/kolabnotes-android/blob/e8ac5992c78de6bd841986da425be9b500e48ed6/app/src/main/java/org/kore/kolabnotes/android/content/NoteRepository.java#L176
- ... which does not take into account the description attribute (the method name gives already a hint)!

**Comment by konradrenner** [comment]
Thanks for the hint! Will fix it as soon as I am back from my honeymoon ;-). I will also create a new issue for exporting categories too.

**Comment by konradrenner** [comment]
will be fixed in next version

**Comment by konradrenner** [comment]
done with 2.1.0
