### ISSUE TITLE
make kolabnotes guam-capable

### ISSUE THREAD

**Issue by mhellwig** [konradrenner/kolabnotes-android#133]
Hi,

we run a kolab server version 16 where guam acts as a proxy that will filter out (or rather show as empty) all groupware-folders as long as you log in claiming to be an email client.

Apparently, if I read things right, you need to tell a kolab server that you are a kolab-client when logging in via imap, but I myself don't know which header you need to set for that.

Anyway. Currently, with our old kolab installation (no guam), I can see all my notes with kolabnotes-android. On our new one (see above), I see "no notes", even though the same ones should be in there.

I use the current kolabnotes-android from f-droid (2.1.0).

**Comment by konradrenner** [comment]
Hi,

thanks for reporting. I already tested the guam support with Aaron Seigo at the moment the first version was released. He said that kolabnotes works with guam, so I am a little bit suprised.
Is it possible that you create a test account on your server for me? So I could test and debug why no notes are synced when guam is active?

Yours, Konrad

**Comment by mhellwig** [comment]
Account created. How/where best to tell you the login details?

**Comment by konradrenner** [comment]
Please send it on this mail address: koni.renner@gmail.com

**Comment by mhellwig** [comment]
Done

**Comment by konradrenner** [comment]
Thank you very much!
First result of my analysis: I get the notes and notebooks, but it is problematic, if the shared notebooks feature is activated. The scan for shared notebooks runs and runs and runs until I stop it in the debugger.

So can you please check, if you get the notes/notebooks if you disable the "Shared notebooks" option in the extended options?

**Comment by mhellwig** [comment]
Created the account (on the phone) anew, this time unchecking the "shared notebooks". Sync still runs for ever, ends with a java.io.IOException: connection dropped by server?

I guess I have to check in which way my account on that server differs from your default one.

**Comment by konradrenner** [comment]
I have found a problem with this option :-), if you uncheck it, it will not have any impact. I will create a new version of the app, where the option is checked correct in the sync progress. Please check the sync after the update again (will publish the update today)

**Comment by mhellwig** [comment]
just to confirm: this works now, thank you!

**Comment by konradrenner** [comment]
Great!
