### ISSUE TITLE
Rotating tablet loses edits

### ISSUE THREAD

**Issue by dkibbe** [konradrenner/kolabnotes-android#134]
1. Start a new note or edit an existing note.
2. Rotate the tablet.
3. Note closes without saving changes.
4. Same thing happens if app is minimized or another app is brought to the foreground.

This happens in Kolab Notes 2.1.1.

**Comment by konradrenner** [comment]
Which Android version do you use?

**Comment by dkibbe** [comment]
The problem seems unique to CyanogenMod. On Android 6.0.1 the app functions correctly. I'll post on the CyanogenMod forum.

Dennis

**Comment by dkibbe** [comment]
Then again maybe its not CyanogenMod. Just tested the app on a Nexus 7 with a fresh install of Android 6.0.1 and get the same behavior as on CyanogenMod. Same app version works correctly on 6.0.1 on a Samsung Note 4.

**Comment by konradrenner** [comment]
Ok I can reproduce it, the Problem only occurs on Tablets, not on Smartphones. @proninyaroslav do you have an idea what the Problem could be? I think you have solved a simliar one for smartphones?!

**Comment by proninyaroslav** [comment]
@konradrenner 
I'll see in the coming days, in what could be the problem. 
P.S: I also push commit with changes for AlertDialog (saving state after rotate).

**Comment by konradrenner** [comment]
@proninyaroslav great thanks!

**Comment by konradrenner** [comment]
Thank you! I will make a new release this weekend!
