### ISSUE TITLE
Remote sync fails

### ISSUE THREAD

**Issue by dkibbe** [konradrenner/kolabnotes-android#135]
## System
1. Fresh install of Android 6.0.1 on Nexus 7
2. Fresh install of Kolab Notes 2.1.1
3. Set contact & storage perms
4. Create KolabNow account named KolabNow, imap.kolabnow.com, MyUserName@libertymail.net, correct password.
5. Sync fails (java.lang.IllegalStateException: korex.mail.MessagingException: connection failure)
## Stats
1. 13.59 MB internal storage used (only 1 short local note was created.)
2. 1.89 MB data used.
3. 44MB average memory used in last 3 hours.

**Comment by konradrenner** [comment]
Thanks for the detailed informations! App size is around 13 MB because of the media which the app contains (eg Icons). The real data useage of stored notes, is the field "data used".

Please try disabling the "enable shared notebooks" switch in the extended options and try to sync again. Please let me know if sync works with this flag disabled.

**Comment by dkibbe** [comment]
Same error message with shared notebooks disabled. IMAP root folder is still the default Notes.

**Comment by konradrenner** [comment]
I can sync with Kolab Now without any problems. I tried it on an Android 5.1.1 smartphone and Android 6.0.1 tablet.

Is it the first time you try to connect to this account or have you already connected to it on another device?

Are you trying to sync via WiFi or mobile internet?

**Comment by dkibbe** [comment]
Sync fails first time and everytime both on mobile Internet on Samsung Note
4 & WiFi on the Nexus 7. Perhaps the problem has nothing to do with the
app. Is there a Kolab test account I can try later?

On Aug 4, 2016 11:03 PM, "Konrad Renner" notifications@github.com wrote:

I can sync with Kolab Now without any problems. I tried it on an Android
5.1.1 smartphone and Android 6.0.1 tablet.

Is it the first time you try to connect to this account or have you already
connected to it on another device?

Are you trying to sync via WiFi or mobile internet?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/konradrenner/kolabnotes-android/issues/135#issuecomment-237763710,
or mute the thread

**Comment by konradrenner** [comment]
I just have my personal account, which I use for testing and "production" and everything works. I am syncing via WiFi and mobile internet without problems.
Can you send me a screenshot of your account settings and a screenshot of the expanded error notification?

**Comment by dkibbe** [comment]
When I tap the Kolab Notes notification I don't get a detailed debug message like I get with OpenTasks/Davdroid. They also have issues syncing so I've included screenshots for that notification. On the Kolabnow site there is a sharing tab for folders and notes which has no entries and can not be changed. On the Folder Properties tab folders are marked Private.

https://github.com/dkibbe/dkibbe.github.io/blob/master/images/kolab-error-kibbe.png
https://raw.githubusercontent.com/dkibbe/dkibbe.github.io/master/images/opentasks-error-1.png
https://github.com/dkibbe/dkibbe.github.io/blob/master/images/opentask-error-2-kibbe.png

**Comment by konradrenner** [comment]
The DavDroid problem is another one, but I think they solved it already?!

Please don't tap on the notifcation, just expand it, like described here: http://www.hongkiat.com/blog/android-notification-features/ (in Point 6) and post a screenshot of it here please

**Comment by dkibbe** [comment]
Here is the complete error message.
https://github.com/dkibbe/dkibbe.github.io/blob/master/images/kolab-error-kibbe-1.png

**Comment by konradrenner** [comment]
Do you sync this account with any desktop mail client eg Thunderbird, KMail? If yes, please check the imap settings and compare it with the settings of your Kolab Notes app, are there any differences?
Do you already have created notes via Web UI?

**Comment by dkibbe** [comment]
I can sync using K-9 or the GMail app. I already had notes before installing Kolab Notes. Since you are able to sync perhaps my situation is unique. Apparently I have other issues. Yesterday Kolab Notes crashed while saving a note with an attached camera image. The app could not be restarted until I deleted the note database losing all my notes. In view of that I'm going to stop using Kolab Notes for now. I do appreciate all  your help. (Konrad, Haben Sie ein BitCoin Konto? I kaufe Ihnen gern ein Bierchen. Dennis)

**Comment by konradrenner** [comment]
I am very sorry that I was not able to help you :-(, but I cannot reproduce your problems and so I cannot solve them. Nein habe ich nicht, aber danke für den guten Willen :-)
