### ISSUE TITLE
Companion app for Linux or Thunderbird Extension ?

### ISSUE THREAD

**Issue by mark-orion** [konradrenner/kolabnotes-android#138]
This is more a question than an issue: This app works great - thanks a lot! But I would like to create, display etc. my notes on my Linux desktop(s). Is there a kind of "companion app" or Thunderbird extension that can do this ?

**Comment by konradrenner** [comment]
Hi, thanks for using the app! If you are using a Kolab server for sync, you can use Zanshin (https://zanshin.kde.org/), it is official client for syncing notes and tasks. 

If you are using a generic IMAP server you can use this app: https://github.com/konradrenner/kolabnotes-fx . The kolabnotes-fx app also works with IMAP server and supports the same things as the app. But be aware that this app is just a playground for me, so there is no deep OS integration and no fancy user interface. It just syncs your notes and let you edit/create/delete them ;-). Important: use the Oracle Java runtime for executing the jar file you find in the GitHub releases tab.
Please let me know if it is useful for you ;-)

**Comment by mark-orion** [comment]
Thanks for the quick reply! Yes I like your app, specially that it is not limited to text like many other note taking apps. Zanshin with the whole KDE behind would be overkill and I am using an ordinary IMAP server anyway, so I tested your java app. It works fine so far, but it does not seem to save the password and is not syncing automatically what is a bit of a showstopper. Ideally I would want something like Tomboy that automatically displays the notes on my desktop, allows editing them and syncs with the server in the background.

**Comment by konradrenner** [comment]
Yep, because it is a just for fun project, I have not implemented the hard parts (brackground sync, password store and other nice OS integration parts ). Maybe when I find some time I will do it :-)

**Comment by konradrenner** [comment]
I have created an issue in the repository of the java app, so if I don't find some time, maybe another one grabs it :-) https://github.com/konradrenner/kolabnotes-fx/issues/1
