### ISSUE TITLE
Resizable widget

### ISSUE THREAD

**Issue by ameenross** [konradrenner/kolabnotes-android#144]
I'd like to be able to downsize the note widget. I have some very small notes that only need to be 1x1.

**Comment by konradrenner** [comment]
I will make it possible with the next release

**Comment by ameenross** [comment]
Awesome :)

**Comment by konradrenner** [comment]
done, already published in play store beta channel. will publish it the coming days in production channel. in f-droid it will be available with the next f-droid app build.

**Comment by ameenross** [comment]
Awesome. I'm using f-droid. Any idea when the next app build will be?

**Comment by konradrenner** [comment]
Hard to say, but I think it will be during the next week
