### ISSUE TITLE
Add Kolab Notes as recipient for image (png/jpg) sharing

### ISSUE THREAD

**Issue by greve** [konradrenner/kolabnotes-android#148]
it would be excellent if it were possible to share one or more pictures to Kolab Notes.

That way it would be possible to just directly share the pictures / scribbles from a session into Kolab Notes and then supplement / complete later on mobile, desktop or web.

**Comment by konradrenner** [comment]
Do you think the image should be "attached as Attachment" or as inline image in the note itself?

**Comment by konradrenner** [comment]
is implemented with the next version (2.5.0) which will be release soon
