### ISSUE TITLE
[Not A Bug] Failed Synchronisation on Android 7.1(CM14.1)

### ISSUE THREAD

**Issue by javiertury** [konradrenner/kolabnotes-android#149]
First, setup an IMAP provider. This pops up after trying to create a note:

```
Synchronisation failed
java.lang.RuntimeException:
java.lang.ClassCastException: java.lang.String cannot be cast to korex.mail.Multipart
```

**Comment by konradrenner** [comment]
Hi,
can you please provide some more informations. Do you host your own server? What kind of IMAP server do you use?

**Comment by javiertury** [comment]
I tested the app using my gmail account. The app read the existing notes but failed to create a new one.

**Comment by konradrenner** [comment]
Did you create "notes" outside the app or with another app which also uses IMAP for sync?

**Comment by javiertury** [comment]
My bad, sorry to make you waste your time. When setting up the account I thought that disabling "kolab extensions" should make it compatible with plain imap notes(iphone like). Now I see that having those notes conflicts with kolab ones which are always stored in kolab format, the extensions must be something that has to do with the server.

I created a new imap folder "KolabNotes" just for kolab notes and solved it, although I now realize that this a specialized app for the kolab environment.

**Comment by konradrenner** [comment]
No time is wasted, I like to help people which want to use the app ;-)

The app uses the Kolab storage format and thx to this it can sync notes with a Kolab server and a "plain" IMAP server. It uses this format because it is not a proprietary format like the Apple notes format, but it would be of course possible to implement the sync with Apple notes, if there is an official and open documentation of the format.

Maybe if you could provide me a link to such a documentation, you can create a new "feature request issue" and maybe this feature request will be implemented ;-). But I think this issue can be closed.

**Comment by konradrenner** [comment]
By the way: the "Kolab extensions" flag just indicates that sync should be done with some Kolab specific IMAP annotations which are not supported by some "plain" IMAP Server (like Gmail for example).

**Comment by javiertury** [comment]
Now that you talk about the apple notes format, they are actually regular emails. If you are curious take a look at:
http://www.shivkaushal.co.uk/blog/2011/01/create-an-iphone-note-from-your-mac-and-push-it-to-gmail/

The only extra headers are these:
```
X-Uniform-Type-Identifier: com.apple.mail-note
X-Universally-Unique-Identifier: <insert UUID here>
X-Mail-Created-Date: <insert date here>
```

They _Subject_ header is the _Summary_ of the note and the body of the message is the body of the note. However I don't think there is an equivalent of notebook, they can't be categorized, because they are very basic.

**Comment by konradrenner** [comment]
So there is also no styling possible in the note text? Or are such notes html based mails?

**Comment by javiertury** [comment]
There is no styling just plain text. On the internet you'll find people messing with html code like http://jpmens.net/2015/09/28/experiments-using-imap-for-notes/

But that is not how it is supposed to work.

**Comment by konradrenner** [comment]
Thanks for the link, I will create a feature request. Maybe some implements it ;-)
