### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by konradrenner** [konradrenner/kolabnotes-android#159]
The used icon (from KJots) does not have the "flat" material style. Take a new icon and also support Android O Adaptive Icons.

I think a good choice is the attached icon from the KDE breeze icons. The breeze icons look really good and are free to use in oss software

.

**Comment by konradrenner** [comment]
[breezeicon.zip](https://github.com/konradrenner/kolabnotes-android/files/887499/breezeicon.zip)

**Comment by konradrenner** [comment]
https://developer.android.com/preview/features/adaptive-icons.html

**Comment by konradrenner** [comment]
files created, but waiting for release of the sdk so that I can put it in the play store, so for the next release just the new icon

**Comment by proninyaroslav** [comment]
Great work! But it would be more canonical if the pen would cast a shadow.

**Comment by konradrenner** [comment]
Yeah, maybe but I am not good at altering graphics :-( and with Android O the icon should get the shadow "for free"

**Comment by proninyaroslav** [comment]
Is there a source code of this icon?

**Comment by konradrenner** [comment]
https://github.com/KDE/breeze-icons/blob/master/icons/apps/48/calibre-ebook-edit.svg

**Comment by konradrenner** [comment]
new icon released, letting this issue open until final android o sdk is available so that the new adaptive icon will be implemented

**Comment by konradrenner** [comment]
New possibilty with Android Studio 3 for designing adaptive icons:

Adaptive Icon Wizard - Android O introduces adaptive launcher icons, which can display in different shapes across different Android devices. The new Adaptive Launcher Icon wizard creates the new and legacy launcher icon assets and provides previews of how your adaptive icon will look on different launcher screen icon masks. Create a new asset by right-clicking on the /res folder in your project then navigate to → New → Image Asset → Launcher Icons (Adaptive and Legacy)

**Comment by konradrenner** [comment]
will be fixed in 3.0.0
