### ISSUE TITLE
"NOT_LOADED" Notes after sync with Kolab 16.0.1-9.3

### ISSUE THREAD

**Issue by jost47** [konradrenner/kolabnotes-android#163]
Hi there,
I've been using Kolab Notes successfully long time now, syncing with my self-hosted Kolab Server.
After upgrading Kolab to 16.0.1-9.3 end of september, I run into an issue when trying to sync:
in Kolab Notes, some notes are not shown anymore (approx. 15% of all notes), but just a title like "NOT_LOADED" is shown. The other notes show up correctly. New notes on the server are not shown at all.
Android gives a error notification each time Kolab Notes tries to sync (manually or periodic):
> Synchronisation fehlgeschlagen:
> java.lang.RuntimeException: org.kore.kolab.notes.v3.KolabParseException: org.apache.harmony.xml.ExpatParser$ParseException: At line1, column 367: not well-formed (invalid token)

I thought of some issues on the server, of course, and tried to sort it out:
- cyrus-imapd log files don't show any errors related to these syncs
- guam logfiles don't show any errors eather.
- restart of cyrus-imaps and/or guam doesn't help
- I was still running guam 0.8.3 because of strange issues with newer guam versions, but
  tried 0.9.2 temporarily nevertheless, just to see if it makes a difference: it doesn't

Don't know if this issue is related to my Kolab update, but I suspect so (just by coincidence).
Now, I don't have a clue what the reason might be, and how to fix it.
Any help is more than welcome!
Thx.

**Comment by konradrenner** [comment]
Hi,
which Android version do you use? Are you using the newest version of the app?
Did you also try to sync the notes via the "Swipe-Refresh gesture"?

It seems like that there is a note, which is not parseable within the app, did you create a note with some "fancy" characters in it?

Yours,
Konrad

**Comment by jost47** [comment]
Thx for your quick response!

The issue was noticed on my Sony Z3C first, it has Sony stock ROM Android 6.0.1.
The App's version is 2.7.2 (I upgraded the app in May already).
Meanwhile I already wiped Kolab-Notes' data, removed the app, and re-installed
from the Play Store: no solution, the issue comes back again. On the first sync
already, approx. 20% of my 80 notes are not shown (just "NOT_LOADED"), but
those not loaded are not the same as before, i.e. some of them were loaded before,
and some of those not loaded do show up now. I don't see a scheme, though...

When trying to sync manually via "Swipe-Refresh gesture", the app takes some time
(approx. 30 sec.) as usual, but the issue is the same: some notes are not loaded.
There is not error message during the time when the app read/writes via network,
only the error message at the end (see orig. post).

Furthermore, I grabbed one of my old phone, too, and installed the app on it.
It is a Google Nexus-S running Android 4.2, and it does show the same issue.

Right now, I don't believe in some "fancy" characters in the notes themselves,
because the issue started when no content changes were done (I am using
notes most of the time just to archive information, therefore notes are not
updated or amended very often. But of course I will check that, too, might
take another day or two. (I will export the notes on the server, and check
a hex dump for something unusual...)

**Comment by konradrenner** [comment]
Really strange. Would it be possible that you create a test account on your server for me? It would then be possible for me, to debug the app.

Another question: Did you try disable the "shared notes" option in the extended options during account creation?

**Comment by konradrenner** [comment]
cannot reproduce it
