### ISSUE TITLE
"Failed to refresh folder "{Account Name}: INBOX"

### ISSUE THREAD

**Issue by clockworkpc** [konradrenner/kolabnotes-android#164]
Ubuntu 16.04
Evolution Mail version 3.18.5.2

Kolabnow settings are standard. (@libertymail.net)

I keep on getting this message.

![screenshot from 2017-11-27 14-18-56](https://user-images.githubusercontent.com/9858440/33249472-d8d6c57c-d37e-11e7-8e01-60ea3ec50a89.png)

However, as far as I can tell, my emails are syncing just fine.

So, everything works, but I get this weird message.

I also synchronise a Gmail account with the same desktop client and do not get this error message.

**Comment by konradrenner** [comment]
Hi,

please report this issue to the Evolution Mail community. I am sorry, but don't see any relation with the Kolab Notes Android app.

Yours,
Konrad
