### ISSUE TITLE
[Question] Sync with another file storages

### ISSUE THREAD

**Issue by Kristinita** [konradrenner/kolabnotes-android#165]
Do you plain add sync notes with any of file storages with the possibility of free accounts as MEGA, Box, Dropbox, Google Drive, Yandex.Disk and so on?

Thanks for the great app.

**Comment by konradrenner** [comment]
Hi,
syncing with file storage is not planned and not a goal of this app. But you can sync notes with this app with free accounts of IMAP services, such as Google Mail, Yahoo Mail and so on.

Yours, Konrad
