### ISSUE TITLE
[Bug] Can't synchronize with Gmail Server

### ISSUE THREAD

**Issue by Kristinita** [konradrenner/kolabnotes-android#166]
### 1. Summary

I don't understand, how I can synchronize my Kolab notes with Gmail. I have similar problem with Yahoo Mail.

### 2. Settings

**Device:**
Samsung GT-I8262
**Operating system and version:**
Android 4.1.2 rooted
**Kolab Notes:**
2.7.2 — latest F-Droid version

#### 3.1. New account

I install Kolab Notes via F-Droid → I create new IMAP Server account:

![New account](https://i.imgur.com/Bi2tgag.png)

+ I wrote my working GMail box,
+ 4 times I check of the password,
+ [**IMAP setting for G-Mail**](https://support.google.com/mail/answer/7126229?visit_id=1-636476453099855476-416066516&hl=en&rd=1)

I get notification:

![Error 1](https://i.imgur.com/Y64yBqp.png)

(I'm sorry, I don't know where's file with stack trace)

#### 3.2. Creating notes

I select my `TestAccount`:

![Account](https://i.imgur.com/1Akh9aM.png)

I create notepad and 2 notes:

![Notes](https://i.imgur.com/Gkt7wux.png)

`Settings` → `Synchronization` → `System Synchronization`:

![System Synchronization](https://i.imgur.com/IVgopms.png)

I select Test Account → Sync → I again get error notification:

![Second error](https://i.imgur.com/5Q5plNY.png)

### 4. Expected behavior

Successful free synchronization.

Thanks.

**Comment by konradrenner** [comment]
Hi,

please create a folder Notes on the top level of your Gmail account and then trying syncing again.
Is it working?

**Comment by Kristinita** [comment]
Thanks! Now synchronization works for me in GMail and Yahoo.

![GMail](https://i.imgur.com/oQIwgdh.png)

It would be nice, if you add information about correct synchronization to README.MD and/or F-Droid.
