### ISSUE TITLE
Request to promote your app sir

### ISSUE THREAD

**Issue by kazimyrex** [konradrenner/kolabnotes-android#175]
Sir I would love to promote this project because have been using it for quite a while now is an easy and light app to understand and use. And my promotion will cover over 10,000 people

**Comment by konradrenner** [comment]
Hi, thank you for your offer! Can you please provide me with some details of your plan? I am always pleased if people like to help me :-)

**Comment by kazimyrex** [comment]
I plan on using my Facebook page to run a promotion for the app which have
already started then talk more about the app on the post also posting it on
the visibility category in the utopian. Io platform
