### ISSUE TITLE
Request to promote your app sir

### ISSUE THREAD

**Issue by kazimyrex** [konradrenner/kolabnotes-android#176]
Sir I made a request and I sent examples of what and how I wanted to Carry out this promotion

**Comment by konradrenner** [comment]
Thank you, I will soon have a look on it

**Comment by kazimyrex** [comment]
OK sir am waiting for your response

**Comment by konradrenner** [comment]
Hi,
I am very pleased if you promote the app, the only condition is, that there must be no costs for the app and this community!

Yours Konrad

**Comment by kazimyrex** [comment]
Agreed I pay all the expenses for the cost of the promotion you won't have
to pay anything
