### ISSUE TITLE
i will love to do copywriting for you 

### ISSUE THREAD

**Issue by hamzeyto** [konradrenner/kolabnotes-android#177]
I love your application and would want to contribute to it, I'm not a developer but I am good at copywriting. I would love to make a copywrite for your Readme and make a pull request for you to merge. Your response would be highly appreciated. Also I would like to request if we could communicate either here or via email, so I don't have to create issues. Thank you.

**Comment by konradrenner** [comment]
Hi,

thank you! The app is already licensed under the LGPL v3.
It would be really cool, if you could write some FAQs or documention how to use the app. This would be really useful!

For communication you can use Slack => kolabnotes.slack.com

**Comment by omideleayo** [comment]
Hi, 
Seems he hasn't done what you asked for, and I think I can add some great documentation for the app. 
May I?

**Comment by konradrenner** [comment]
This would be great, just send a pull request :)

**Comment by omideleayo** [comment]
Sure, thanks would send a pull once done
