### ISSUE TITLE
AWESOME LOGO DESIGN FREE FOR YOU 

### ISSUE THREAD

**Issue by abdulmalikkhan655** [konradrenner/kolabnotes-android#178]
Hello, @konradrennerI want to contribute in "kolabnotes-android" so i  want to designed a new logo for "kolabnotes-android" and it's free.

I hope you like it. If you like it, I will send you pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.
if you want i will send you my design

contact me on facebook for fast delivary 
https://www.facebook.com/abdulmalikkhan655

**Comment by konradrenner** [comment]
Hi, thank you! But I don't have a Facebook account. Can you please attach a preview of the logo to this issue?

**Comment by chesio** [comment]
@konradrenner, I'm afraid this is just a scam of some sort, see: https://github.com/andOTP/andOTP/issues/180

**Comment by abdulmalikkhan655** [comment]
@konradrenner  sir i will send you preview logo as soon as and thanks for contact me

**Comment by abdulmalikkhan655** [comment]
![11](https://user-images.githubusercontent.com/36396753/40127877-cf95e1f4-5949-11e8-9c8d-2ffc4772bc8c.png)

Hello @konradrenner  this is my logo design select your favorite logo . If there's something you want to change, I'll do it.

**Comment by konradrenner** [comment]
Thank you very much for your effort! But I think the actual logo is best suited to the requirements
