### ISSUE TITLE
Viewing a note updates its last modified time

### ISSUE THREAD

**Issue by AaronM04** [konradrenner/kolabnotes-android#180]
Hi all. I have an issue with the 3.1.3 version that is significantly degrading usability. If I click on a note, the note goes to the top because viewing is now counted as modification. This did not happen with the previous version of Kolab in f-droid (2.7.2). Due to an error, I cannot rollback.

**Comment by konradrenner** [comment]
Thx for reporting, will have a look at it soon!

**Comment by konradrenner** [comment]
should be fixed with latest release
