### ISSUE TITLE
Kolab Notizen v 3.1.3 Crash when select and open the Print feature in android 7.0

### ISSUE THREAD

**Issue by ammarraisafti** [konradrenner/kolabnotes-android#186]
# Expected behavior
When selecting and opening the Print feature, the user should be redirected to the Save as PDF or All Printers page. So users can set Paper size, Orientation, Color and more. Before starting Print.

# Actual behavior
When selecting and opening the Print feature, the app suddenly crashes and stops.

# How to reproduce
* Launch app. 

* Click the top right shortcut, then select and open the setup feature.

* Select and open General feature, then Disable all features in it, except feature Show metainformations.

* Return to the previous menu, or to the main view open the app.

* Click the top right shortcut, then select and open the New notebook feature.

* Enter the name of the new notebook, then click Ok to save it.

* Then click the pencil icon to add a summary.

* Click the top right shortcut, then select and open the Print feature. Problems coming soon. *The application suddenly crashes and stops.*

<center>Browser: Samsung Galaxy S6 edge
Operating system: Nougat 7.0
App version: 3.1.3</center>

# Recording Of The Bug
https://youtu.be/A-MnGoJvL2M

# Proof of work done
 https://github.com/ammarraisafti

**Comment by konradrenner** [comment]
Thank you for the detailed infromations about the problem! I think the problem is, that you want to print an empty note (why do you want to do that?).

So the print button should be disabled if the notes is completly empty.

**Comment by konradrenner** [comment]
Do you have disabled the rich text editing feature? 

Maybe this issue has the same source problem as issue #197

**Comment by ammarraisafti** [comment]
Yes, it looks like this problem happened because I have disabled the "Enable Rich Text Editor" feature.

**Comment by konradrenner** [comment]
will be handled with issue #197
