### ISSUE TITLE
Proposal Add Backup Feature In Kolap Netizen app

### ISSUE THREAD

**Issue by rezamusic881** [konradrenner/kolabnotes-android#189]
#### <center>Component</center>
<P>
<div class="text-justify">Translate the description back into Germany (Germany)
Note the Kolab open source notepad is an application that allows notes with Kolab or IMAP server to synchronize.</div>

<P>
<div class="text-justify">The coolest feature of many functions of this application, such as:
Materials Design, add, edit and delete notes, creating and deleting notebooks, add, edit, and delete categories/tags, records management using notebooks, records management use the categories/tags, support split notebook with a Kolab Server (thanks to Daniele Gobbetti for test account!), every note can be set to color, each category can be booked for a color, locate records,  "Label " widget for display or link the record on the home screen, the list of widget to display the list of configured entry on the home screen, support for multiple accounts, synchronization with Kolab or IMAP server at Kolab v3 Format Storage, thanks to local Records local accounts, Tablet UI, rich text Capture and Image Editing in text, some notes (thank Yaroslav Pronin!), import/export, Print Notes notebook (thank Yaroslav Pronin!), handwritten notes/images (thanks Yaroslav Pronin!), annex notes and provide translations of various languages like (Germany, United Kingdom, Russia, France, Italy, Viet Nam, Japan.</div>

***

#### <center>Proposal</center>
<P>
<div class="text-justify">In this contribution I want to give feature suggestions to the kolab notizen applications.</div>

<P>
<div class="text-justify">In my opinion, such applications really need "feature Backup", because after the user generally thought to install this application for storing important data or daily schedule. By because it's "feature Backup " is very important in this application.</div>

<P>
<div class="text-justify">In the review of the functions,  "feature backup" is to move or copy a collection of information (data) stored in the hard drive of the computer that is usually done from one location/location/device to another device. So this idea that match.</div>

***

###### <center>Just click on the  "feature Backup ", then all data will be downloaded automatically stored on the device file manager.</center>

![bd79cf63-fab4-4223-8c29-1f58d847c42c (1).jpg](https://cdn.steemitimages.com/DQmaVCMQTtqNgi975W1UNwDPcZDs9J5GhbqBexoGLmhZ3ad/bd79cf63-fab4-4223-8c29-1f58d847c42c%20(1).jpg)

***

#### <center>Benefits</center>
<P>
<div class="text-justify">Benefits of Backup features: The usefulness of backup features or benefits i.e. we still have backup data from data lost/corrupted/deleted, whether caused by our own fault or other factors beyond our ability, such as: infected with a virus, corrupted file (not be opened), device error/problematic, disaster, etc.</div>

<P>
<div class="text-justify">With the backup data is already so we save those we can use as a substitute for data that has been lost/damaged/erased. More data backup function refers to a factor of security and comfort in using the application.</div>

**Comment by konradrenner** [comment]
Thanks for reporting! The possibilty to create and read backups is already possible. Just select the export/import notebook menu.
