### ISSUE TITLE
App crashes when adding a new note

### ISSUE THREAD

**Issue by lhitc** [konradrenner/kolabnotes-android#19]
When no notebook is selected (e.g. no notebook exists), the "add note" button is available in the app.
When tapping the button, the app crashes.

I would expect to have either a hint "Please add a notebook before adding notes" or have the button disabled.

**Comment by konradrenner** [comment]
Fixed in current master, will be available in the next preview version. When no notebook exists, there will be a dialog for creating a new one, before one can create the note
