### ISSUE TITLE
Data lost after sync error

### ISSUE THREAD

**Issue by sdaro** [konradrenner/kolabnotes-android#195]
I applied a lot of changes to my notes and categories.
After the sync a error message was shown with an exception.
All my changes were lost.

My selected strategy was to take the last edited note in case of a conflict.
I'm using Kolab-notes only on one device.
That's why I don't understand that all my changes are missing now.

When an exception is thrown there shouldn't be a data loss. As a user I expect the same app state as before the failed sync.

**Comment by konradrenner** [comment]
Hi, I am very sorry for the data loss. Normally this shouldn't happen. Do you sync your notes with a Kolab or simple IMAP server?

**Comment by sdaro** [comment]
I'm syncing with a simple imap server.

**Comment by konradrenner** [comment]
Can you please provide more informations like error logs, your device and Android version. Did you manual start the sync?

**Comment by sdaro** [comment]
Where can I find the error logs?

I have a Sony Xperia Z1 Compact. Model D5503. Android v5.1.1

**Comment by sdaro** [comment]
I didn't start the sync manually.

**Comment by konradrenner** [comment]
errors are displayed in the notifcation area of android. On you imap server: can you see the notes folder you specified? are there mails in it?

**Comment by sdaro** [comment]
The notification is gone and I couldn't reproduce it yet.
I see the the folder in the notes folder and there are mails inside.

**Comment by sdaro** [comment]
I turn the flight mode on in the night and the error happend at night. Maybe it waits for connection and runs in a timeout?

When I turn my phone in flight mode and trigger the sync, it waits until the connection is back again. Maybe after an hour it will fail?!

**Comment by konradrenner** [comment]
If you disconnect from your server and then recreate the account on your phone, are the notes back?

**Comment by sdaro** [comment]
Yes, the (old) notes are back.

**Comment by konradrenner** [comment]
Maybe a temporary problem
