### ISSUE TITLE
Kolab Notizen v3.2.0 - Disabling the "Enable Rich Text Editor" feature, making this application suddenly stop

### ISSUE THREAD

**Issue by ammarraisafti** [konradrenner/kolabnotes-android#197]
# Actual behaviour
It should, after disabling the "EnableRichTextEditor" feature. This application still works well.

# Expected behaviour
After successfully disabling the "EnableRichTextEditor" feature in the application / general settings section.  I tried adding "New Notebook", then accessing the edit icon.  And after I successfully entered the edit icon, I tried to return to the previous menu.  Unfortunately, this application suddenly stopped.

# Step to reproduce
- Install and open the application. 

- Click on the top right shortcut, then select and open the "Settings" feature.

- Select and open the "General" feature, then disable the "Enable Richtexteditor" feature.

- Exit the application settings, then go to the main page / Local account.

- Click the top right shortcut, then select and open the "New notebook" feature. 

- Next you need to fill in the name of the notebook, then click okay. 

- Click "icon edit" the visible on the bottom / right side.

- Then you have to click the back button on the device, to return to the previous menu.

# Information
- Device: Nubia n2 lite 
- Android version: 8.1.0 
- Application version: 3.2.0

# Recording of the bug
https://youtu.be/d9JK0CkZtfU

**Comment by konradrenner** [comment]
Wow, thank you for the the detailed report. I will soon have a look at it

**Comment by konradrenner** [comment]
I can confirm the issue. The bug occurs if rich text editing is disabled an the back or print function is used.

There is no check for this 2 functions if rich text editing is disabled (!Utils.getUseRicheditor(activity)).

NullPointer when print is used:
at org.kore.kolabnotes.android.fragment.DetailFragment.printNote (DetailFragment.java:1563)

NullPointer when back is used:
at org.kore.kolabnotes.android.fragment.DetailFragment.onBackPressed (DetailFragment.java:1494)

**Comment by ammarraisafti** [comment]
Thank you for confirming this problem.  Speaking of code, I don't understand that. 
I hope that this problem solving can be done.  Because I really enjoy this application, and have invited several other users to use this application, also giving the best rating for application.

**Comment by konradrenner** [comment]
I am glad that the app is useful for you!

It should be no problem to solve the problem, but please be patient, I am short on my time at the moment

**Comment by ammarraisafti** [comment]
Yeah, okay. I will be happy to wait.

Pada tanggal Sel, 2 Jul 2019 00.46, Konrad Renner <notifications@github.com>
menulis:

**Comment by konradrenner** [comment]
will be fixed in 3.2.1

**Comment by konradrenner** [comment]
published new release, will be available soon
