### ISSUE TITLE
Kolab Notizen v3.2.0 - Clicking on the widget to enter the application can make this application suddenly stop

### ISSUE THREAD

**Issue by ammarraisafti** [konradrenner/kolabnotes-android#198]
# Actual behaviour
It should be, after I add the widget, then click on the widget to enter the application, and delete the notebook.  The ability to enter applications through widgets must be done.

# Expected behaviour
This application suddenly stopped when I clicked on the widget to enter the application.  Even though I have tried doing it repeatedly, the same problem still occurs.

# Step to reproduce
- Install and open the application.

- Add a new notebook, click the pencil icon, add a summary, then exit the application.

- Add a 2x2 sticky notes collage widget.

- Click on the widget to enter the application, delete the notebook you have created.

- Exit the application, then click on the widget to enter the application again.  Then you will find problems like I have experienced.

# Information
- Device: Nubia n2 lite
- Android version: 8.1.0
- Application version: 3.2.0

# Recording of the bug
https://youtu.be/zc7kxxzqQXY

Beginning of crash
https://cdn.steemitimages.com/DQmU2z8BZVJWu6KYRFEW2uKtoPQJRYvBsPqjhRH6ATGjJTA/Screenshot_2019-07-01-23-23-08.png

https://cdn.steemitimages.com/DQmQfY5JwWuGoWxnMScGAD5RGMG4xuBgck4vwGm2n3fp9od/Screenshot_2019-07-01-23-23-37.png

https://cdn.steemitimages.com/DQmZTJ98Uu4JeWMtvUkMwqRXVyjmuZEGJ2v9dHVu87EA2sf/Screenshot_2019-07-01-23-24-01.png

https://cdn.steemitimages.com/DQmU1JwBbDSLJRDgG3dqwQw3D49VmCt18dEUUgZ8Uo932cB/Screenshot_2019-07-01-23-24-33.png

**Comment by konradrenner** [comment]
Thank you for reporting. Will have a look at it

**Comment by konradrenner** [comment]
Bug accepted, it should not be possible to open a non existing note

**Comment by konradrenner** [comment]
will be fixed in 3.2.1

**Comment by konradrenner** [comment]
published new release, will be available soon
