### ISSUE TITLE
NOT_LOADED notes with IMAP sync

### ISSUE THREAD

**Issue by mathstuf** [konradrenner/kolabnotes-android#202]
I'm trying to sync with fastmail's Notes support (which is over IMAP), but I am seeing server-side notes locally as `NOT_LOADED` and local notes don't seem to get uploaded at all. I disabled Kolab extensions and Sharing support.

Also, it seems that a `Configuration` folder always gets created server-side. Is there a way to suppress that?

Using version 4.0.0 from F-Droid. I see some discussion in #142 which is similar, but the recommendations there do not work for me. Any way to get more information from the app?

**Comment by konradrenner** [comment]
The configuration folder is needed by the app.

What do you mean with "server-side notes"?

**Comment by konradrenner** [comment]
Did you create notes with another app and sync it with your account?

**Comment by mathstuf** [comment]
I made the notes using the web editor from Fastmail. They appear in my mail program as well as normal email messages.

**Comment by konradrenner** [comment]
I am sorry to tell you, that are just notes in the Kolab V3 storage format are supported. I don't think fastmail will use this format.

So, at the moment, it is technically just not possible to view/edit notes in other formats.
The NOT_LOADED is therefore an absolutley correct behaviour.

But I would be very pleased, if I get an pull request with support of other formats ;-)
