### ISSUE TITLE
Can't sync with imap

### ISSUE THREAD

**Issue by dgleba** [konradrenner/kolabnotes-android#211]
I am trying to sync. Nothing syncs.

I get no error message.
Notes folder exists on outlook.com

I use this..
```
Server address: imap-mail.outlook.com
Port: 993
Encrypted Connection: SSL
User name: Your full Hotmail email address, including ‘@hotmail.com’.
Password: Your Hotmail account password
```

I also tried with my local service wightman.ca with no success.

Can someone help?

**Comment by konradrenner** [comment]
Hi, have you disabled "Shared notebooks" and "Kolab extensions"?

**Comment by dgleba** [comment]
I have done that. Nothing syncs.

I have two phones setup to sync with different notes. There are two more differert notes in the Notes folder of Outlook.com mail.

I wonder if there are any error messages somewhere I can read them.

**Comment by konradrenner** [comment]
Is the Notes folder a top level folder?

What kind of notes are inside your notes folder? Did you create them with Kolab Notes or any other App?

**Comment by dgleba** [comment]
![image](https://user-images.githubusercontent.com/4622715/93005812-ca4da200-f522-11ea-8c97-697232b75a15.png)

https://photos.google.com/photo/AF1QipPClIVcGegdRGTmhKlVXIvx1JPiu5wQEtYxK1JQ

https://photos.google.com/photo/AF1QipNTmfheY_PRC-VT7nZyazDvGgAk8CeI0nYjqLSr

**Comment by dgleba** [comment]
https://photos.google.com/photo/AF1QipO0QELVWNkmwPEVNg8Y_gI_nkipU66UpK3XSSp0

https://photos.google.com/photo/AF1QipN1v7zX-OE0lP6YJlOJ92pueVqv2b512ZpooNmy

**Comment by dgleba** [comment]
I created the notes you see in outlook using the new note button in  outlook.

The notes on the phones were created there, except the cnn link was shared from a browser.

**Comment by konradrenner** [comment]
Ok, I understand. I am sorry to tell that this scenario is not supported. Outlook notes and Kolab notes are a completely different format. So it won't work...

**Comment by dgleba** [comment]
thanks.
Another issue said yahoo and gmail did work. I will try those.

**Comment by konradrenner** [comment]
I think outlook should also work, but sync will just work with notes which were created in Kolab Notes format.

Please be aware that this is also true e.g. for Gmail. Notes which are created with Google Keep will not be synced, just Kolab Notes.

**Comment by dgleba** [comment]
thanks.
