### ISSUE TITLE
NotesBook

### ISSUE THREAD

**Issue by ghost** [konradrenner/kolabnotes-android#212]
Hello and thank you for this,

Can you please see why we cant access other notebooks withing the imap/kolab account ?

Anything outside of the notebook Notes, doesn't appear ...

Regards

**Comment by konradrenner** [comment]
Hi,

you have to create a separate account for each "top level notebook/folder".
During account creation, open the "extended options" and put the folder name of your notebook in the appropriate field.

Please let me know if this works for you.
