### ISSUE TITLE
Unable to sync with mailbox.org IMAP

### ISSUE THREAD

**Issue by tombreit** [konradrenner/kolabnotes-android#214]
Dear konradrenner, 

I've set up a new account in KolabNotes (Type: IMAP-Server; Account extensions: disabled, Shared Notebooks: disabled), created the IMAP-top-level directory ``Ǹotes`` but could not sync the notes from my Android device to my mailbox.org IMAP-Account. Notes from ``KolabNotes`` do not show up in my mailbox.org account. 

I do not get any error message when forcing a sync in Android > Settings > Accounts > my-mailbox.org-account (Kolab Notes) > Sync now.

**Comment by konradrenner** [comment]
> Notes from KolabNotes do not show up in my mailbox.org account.
Do you mean that notes are not displayed as "mails" in your accout, or are you using a notes app from your mailbox.org and this app does not show the Kolab notes?

**Comment by tombreit** [comment]
Dear konradrenner, 
correct, notes created via KolabNotes on Android(11) do not show up as emails in my  mailbox.org IMAP folder (Notes or INBOX.Notes). The Android system accountsync-thing for this KolabNotes account states that there was a sync ("Zuletzt synchronisiert: 13. Oktober 2020, 17:13). 

I do not use any Notes app from mailbox.org (as I did not find any;-)).

**Comment by konradrenner** [comment]
can you please send me a screenshot of your settings, so that I can check them?

**Comment by tombreit** [comment]
Sure (sorry, only in german):
 
![image](https://user-images.githubusercontent.com/1015232/96285191-e7243c00-0fde-11eb-8128-0830e9e89552.png)

![image](https://user-images.githubusercontent.com/1015232/96285148-d8d62000-0fde-11eb-973f-1bbcda8a050d.png)

Thanks a lot for your support!

**Comment by konradrenner** [comment]
Dann in Deutsch weiter :-) : Hast du den Benutzername inkl. Domain angegeben (also bspw. meinuser@mailbox.org)?

**Comment by tombreit** [comment]
Hi, ja, den Benutzernamen habe ich komplett angegeben - nutze jedoch eine eigene Domain bei mailbox.org. Mein Benutzername ist daher "foo@custom-domain.de".

**Comment by konradrenner** [comment]
Ich denke das der Login funktioniert, ansonsten würde es nämlich zu einer Fehlermeldung kommen. Was mir noch aufgefallen ist: manche Mailserver trennen die Ordnerstruktur nicht mit . sondern mit / . Hast du auch schon versucht INBOX/Notes in der App zu konfigurieren?

**Comment by tombreit** [comment]
Ja, das scheint bei mailbox.org der Fall zu sein: 
```
imap://username@imap.mailbox.org/INBOX/Notes
```

... aber auch ein neues IMAP-Konto in KolabNotes mit dem Pfad ``INBOX/Notes`` führt zum selben Verhalten wie bisher: 

* Notiz in neuem Konto anlegen
* Synchronisieren -> keine Fehlemerldungen
* IMAP-Verzeichnis der Notes weiterhin leer

Aber ist auch nicht so wichtig - heißt ja schließlich "KolabNotes" und nicht "Mailbox.orgNotes";-)

**Comment by konradrenner** [comment]
Es gibt aber definitiv User die mit Mailbox.org syncen, deshalb verstehe ich es nicht warum es bei dir nicht funktioniert :-) . Funktioniert der sync eigentlich mit anderen IMAP Clients? Bzw. unterscheiden sich die Einstellungen?

**Comment by tombreit** [comment]
Hallo konradrenner, 
danke für deinen support. Ich habe den sync mit IMAP nun nicht weiter verfolgt nutze jetzt eine Notes-App, die auf owncloud aufsetzt.
