### ISSUE TITLE
Note closes (or app crashes?) when I type %

### ISSUE THREAD

**Issue by JDeeth** [konradrenner/kolabnotes-android#215]
Using the MessagEase keyboard on Android - when I type `%` in the body of a note, the note closes (and discards anything I'd written since the last save).

**Comment by konradrenner** [comment]
This is a bug in the Richtexteditor which is used by this app: https://github.com/wasabeef/richeditor-android
If you disable the "Richtext" option in the general settings, the problem does not occur.

Please file a bug in the corresponding project.
