### ISSUE TITLE
pt-rBR Bug

### ISSUE THREAD

**Issue by RickyM7** [konradrenner/kolabnotes-android#216]
When the note classification function is changed to Ascending or descending in the pt-BR language, the app closes and no longer opens.  Another thing is that no option in "Column" and "Direction" is pre-selected.

App: v4.2.0 (Play Store)

**Comment by RickyM7** [comment]
I believe that the bug happens because of these two strings that I translated, apparently this was not supposed to be translatable.

`<string-array name="pref_direction_values">`

`<item>CRESC</item>`

`<item>DECRESC</item>`

**Comment by konradrenner** [comment]
Thanks for the analysis. I will fix it asap

**Comment by konradrenner** [comment]
Fixed with 4.2.1
