### ISSUE TITLE
cant sync with posteo notes

### ISSUE THREAD

**Issue by ghost** [konradrenner/kolabnotes-android#219]
I don't get any errors when I try to add my posteo account, but apps created in the web client don't show up in the app and notes created using the app don't show up in the mail client. This could be related to [#150](https://github.com/konradrenner/kolabnotes-android/issues/150)  as posteo is compatible with apple notes.

**Comment by konradrenner** [comment]
Hi, Kolab Notes just shows notes created in the Kolab v3 storage format. 
Maybe someone implements #150 , but I can't because I don't have any Apple products in use.
