### ISSUE TITLE
Add a configuration option "sync interval" for each Kolab account

### ISSUE THREAD

**Issue by lhitc** [konradrenner/kolabnotes-android#22]
I don't know the (hardcoded?) sync interval yet, but it would be nice to have the interval configurable.
Either via a selection (multiple steps from 5 minutes to 24 hours) our simply by entering the number of minutes.

**Comment by konradrenner** [comment]
Yep sync intervall is actually hardcoded a day. But it should be configureable.

**Comment by konradrenner** [comment]
implemented in current header
