### ISSUE TITLE
Note that was added in the app got deleted while syncing

### ISSUE THREAD

**Issue by lhitc** [konradrenner/kolabnotes-android#23]
I added a note in the app (preview 3), then clicked "sync now" in system settings - accounts - [the configured Kolab account].
The app crashed and the note was gone.

This is currently not reproducible. On a second try, sync was successful and the note was transferred into the Notes IMAP folder.

**Comment by konradrenner** [comment]
I cannot reproduce the problem. Please reopen, if it occurs again
