### ISSUE TITLE
Layout of note list unclean

### ISSUE THREAD

**Issue by lhitc** [konradrenner/kolabnotes-android#25]
The list of notes is not separated, the single notes overlay each other.
Possibly happens when note titles require more than a single row to display and/or the list is longer than the screen

**Comment by konradrenner** [comment]
I know this kind of problem and I am already working on it. But I cannot reproduce it always.

I think the problem is that the refresh of the list is not 100% perfect.

Sadly I have tried already some things, but nothing resolved it. Of course I will continue to work on a solution

**Comment by konradrenner** [comment]
I think this problem is solved in current master, it was a problem with the animations
