### ISSUE TITLE
Ask before a note is discarded

### ISSUE THREAD

**Issue by lhitc** [konradrenner/kolabnotes-android#27]
When hitting the back button accidently while editing a note, all changes are lost immediately.
The app should ask whether the user wants to save or discard the changes.

**Comment by konradrenner** [comment]
I think, the dialog should just appear if any data was changed. 
If one just wants to look into the details of a note, the dialog will be anoying.

**Comment by lhitc** [comment]
Of course, asking for save makes only sense when something has been changed ;-)

**Comment by konradrenner** [comment]
fixed in current master
