### ISSUE TITLE
Batch update of notes

### ISSUE THREAD

**Issue by konradrenner** [konradrenner/kolabnotes-android#28]
If one makes  a long touch on a note in the overview, a batch mode should start. The Toolbar should change and at least support batch deleting, changing tags, changing classification, changing color and moving to another notebook for all selected notes.

**Comment by proninyaroslav** [comment]
Hello. I have time to deal with the addition of Action Mode to the application. As I understand it, for list notes use RecyclerView, but here functional is lean and unlike the ListView does not have multi-selection mode. For multi-selection RecyclerView suggest using this lib https://github.com/bignerdranch/recyclerview-multiselect
What do you think on this score?

**Comment by konradrenner** [comment]
I would say: let's try it ;-)! Really cool that you have time to work on it, have a lot of fun with coding :-)
