### ISSUE TITLE
Sync apparently happens in the wrong direction

### ISSUE THREAD

**Issue by lhitc** [konradrenner/kolabnotes-android#29]
Two days ago I added a note in the app. Yesterday I edited it, today I aee the original text of the note.
Apparently the old version has been synced back from the Kolab server (despite being invisible there, as described in snother issue) while it should have been written to the server.

**Comment by lhitc** [comment]
Sigh, my fault. The old version of the note appeared on a different device than the one I edited on (yes, I actually use the app on two devices in parallel ;-)

But meanwhile, on day 3 of that special note mentioned above, it has completely gone. Meaning: It is visible on none of the two android devices nor via Roundcube and even got deleted from the IMAP storage, according to Thunderbird. Deletion was definitely not done manually.

This is a massive showstopper located somewhere in the sync algorithm. Possibly this may be an issue in Kolab syncing, not in the app?

**Comment by konradrenner** [comment]
please test the fourth preview, i have made some changes in the sync algorithmus. I cannot reproduce this problem :-(

**Comment by konradrenner** [comment]
@lhitc Does this issue occur in one of the versions which you can get on Google Play as tester?

**Comment by konradrenner** [comment]
Known sync problems are handled in Issue #51
