### ISSUE TITLE
Note content uses only half of the screen

### ISSUE THREAD

**Issue by lhitc** [konradrenner/kolabnotes-android#3]
When viewing/editing a note, the note text body begins at about halfway down the screen, leaving a big blank space below the note's title.

**Comment by konradrenner** [comment]
I know, at the moment the standard "EditText" view from Android is used. I will replace this one with a rich text editor view. The details activity is just a "first throw", also the notebook selection will be adopted because I think it looks ugly at the moment

**Comment by konradrenner** [comment]
Fixed in master. RichText-Editor is not included, but we work on it
