### ISSUE TITLE
More advanced search

### ISSUE THREAD

**Issue by konradrenner** [konradrenner/kolabnotes-android#36]
At the moment it is just possible to search for notes with summary. Also it is a ugly search dialog used.

It should be the Android search view being used and the search should be more dynamic, maybe configureable (search in tags, description, etc)

**Comment by konradrenner** [comment]
http://developer.android.com/guide/topics/search/search-dialog.html
We should use the SearchWidget

**Comment by konradrenner** [comment]
Hi,
I have merged your commits and tested it a little bit. Great work so far!
But I have found 3 issues:
1. On a smartphone if you searched for notes, go in detail and then back, the search field is active with the previous search, but all notes are displayed
2. On the tablet if you searched for notes and then want to go in a detail of a note, the detail is showed very short and then the "select a note" fragment is displayed, but the toolbar remains as you were still in the detail
3. It is possible to start a search when you have selected a note (what is good), but when you touch the search menu entry, the note is unselected (the "select a note" fragment is shown) and it is not possible to enter the search, you have must again touch teh search menu entry

Is it possible to fix this issues for you?

**Comment by ninjahoahong** [comment]
@konradrenner Ok, I see. I will look on the problem and update it.

**Comment by ninjahoahong** [comment]
@konradrenner I have fixed the issues, now the search results retained and you can search from details in tablet.

**Comment by konradrenner** [comment]
@ninjahoahong awesome work! will create a new release today.

**Comment by ninjahoahong** [comment]
@konradrenner nice, thank :+1:

**Comment by konradrenner** [comment]
@ninjahoahong is it possible to add the voice search AS describe here http://developer.android.com/guide/topics/search/search-dialog.html#VoiceSearch and the suggestions AS described here http://developer.android.com/guide/topics/search/search-dialog.html#SearchSuggestions ?

That would be super awesome ;-)

**Comment by ninjahoahong** [comment]
@konradrenner I will look into those.

**Comment by konradrenner** [comment]
Great!

**Comment by konradrenner** [comment]
@ninjahoahong if someone really needs voice search, there should be a new issue. So I close this one.

**Comment by ninjahoahong** [comment]
@konradrenner yes, that would be clearer, thank you.
