### ISSUE TITLE
Integrate a rich text editor

### ISSUE THREAD

**Issue by konradrenner** [konradrenner/kolabnotes-android#4]
Integrate or implement a rich text editor which supports rich text as formatted by Kolab libraries (HTML-Format). Replace the EditText-View of the description field with the richt text editor in the DetailsActivity.
Good starting point is maybe here: http://stackoverflow.com/questions/26712606/simple-richtext-editor-in-android

**Comment by konradrenner** [comment]
https://github.com/wasabeef/richeditor-android

**Comment by konradrenner** [comment]
More links:
http://blog.stylingandroid.com/introduction-to-spans/
http://developer.android.com/reference/android/text/Html.html
http://developer.android.com/reference/android/text/SpannableStringBuilder.html

**Comment by grote** [comment]
Currently, notes from Kolab Now are shown in HTML source code. I guess this is the same issue.

**Comment by konradrenner** [comment]
Yep, this is this issue. But with the second preview the HTML tags should be gone (they will not be deleted, just not shown in the plain text. Some tags will already be Interpreted)

**Comment by konradrenner** [comment]
Many styling informations, when created via Kolab Webclient, are not displayed correct. Check this link:
http://stackoverflow.com/questions/5264162/how-to-retrieve-html-content-from-webview-as-a-string
or try this code:
TextView desc = (TextView) findViewById(R.id.desc);
desc.setText(Html.fromHtml(Html.fromHtml(MY_HTML_STRING_HERE).toString()));

**Comment by konradrenner** [comment]
Integrated https://github.com/wasabeef/richeditor-android
