### ISSUE TITLE
author advises to "send a message" when wanting to test. There is no way to "send a message" on github

### ISSUE THREAD

**Issue by mhellwig** [konradrenner/kolabnotes-android#40]
I understand there used to be but afaict this was discontinued some time ago. Since I can't find an email address or twitter handle linked to from this github repo I am unsure how the author envisions me sending him a message. 

I'd be very interested in testing the app, though.

**Comment by konradrenner** [comment]
Hi, thank you for your interest! I will adopt the Readme (I thought it would be possible to send message, between GitHub accounts).
I have created a Google+ community where you can find the link to participate as tester for the app: https://plus.google.com/communities/104269026777633030855 (if you want to get updates and install via Google PlayStore it is necessary to join the group, this a Google policy...).
If you don't want to use Google+ I can send you an apk, but I think it will be better to join the group.
