### ISSUE TITLE
Is com.github.konradrenner:kolabnotes-java:0.6.3 identical to org.kore.kolab.notes:kolabnotes-java:0.6.3?

### ISSUE THREAD

**Issue by ghost** [konradrenner/kolabnotes-android#43]

**Comment by konradrenner** [comment]
yes, it is identical. if you want to use kolabnotes-java via jitpack.io, you have to specify the groupId with "com.github.konradrenner". if you use kolabnotes-java eg via local maven repository, you can specify the groupId with "org.kore.kolab.notes".
