### ISSUE TITLE
Edit Account

### ISSUE THREAD

**Issue by aseigo** [konradrenner/kolabnotes-android#45]
Despite quite a bit of looking around in the UI, I could not find any way to edit an existing account. If this is implemented somewhere, it evidently needs to be made more obvious ...

**Comment by konradrenner** [comment]
It is just possible to delete an add accounts, this feature is not implemented yet.

**Comment by Anisotropic** [comment]
Really need this function.

**Comment by konradrenner** [comment]
Next version will get this ability

**Comment by konradrenner** [comment]
However, it will not be possible to change the root folder or the email because all the data depends on these two properties
