### ISSUE TITLE
Account name / address redundancy navigation drawer

### ISSUE THREAD

**Issue by aseigo** [konradrenner/kolabnotes-android#46]
In the header of the slideout nav drawer, the account name and the account address are both shown. When those are the same, it looks fairly redundant and unpolished :) It would be nice to not show the address if it is identical to the account name. In fact, I wonder if an account name is needed at all, or if the address would suffice in all cases, making configuration that much quicker?

**Comment by konradrenner** [comment]
If the account name is the same as the address, it would be nicer to display it just one time, so this is of course a point which should be fixed.

But I don't think that the address can always replace an account name. My idea is, that one can specify 2 accounts for the same address, please look into Issues #48  for my idea.

**Comment by konradrenner** [comment]
I have implemented a check, if the email is the same as the account name, if this is true, just the email is shown.

It will be available with the next version of the app (0.1.0-beta5), which I will release in this week
