### ISSUE TITLE
Autodetect folders with notes in them

### ISSUE THREAD

**Issue by aseigo** [konradrenner/kolabnotes-android#48]
It is possible to detect which folders have notes in them. This would alleviate the need to set the root notes folder (even if the default is usually correct) and, more importantly, remove the requirement that to be seen all notes folders must be children of that one top-level folder. Given that by default the web UI does not do this, this would make a nice improvement to the user experience when using both the web UI and the Android app.

The way notes folders are detected (and all other similar folders) is to get the metadata for folders (yeah .. all of them .. hooray! :) for the following keys:

/shared/vendor/kolab/folder-type
/private/vendor/kolab/folder-type

The values according to libkolab (Qt/C++ lib used by various bits of Kolab clients):

static const struct {
  const char *name;
  const char *label;
} folderTypeData[] = {
  { KOLAB_FOLDER_TYPE_MAIL,    ""                      },
  { KOLAB_FOLDER_TYPE_CONTACT, I18N_NOOP( "Contacts" ) },
  { KOLAB_FOLDER_TYPE_EVENT,   I18N_NOOP( "Calendar" ) },
  { KOLAB_FOLDER_TYPE_TASK,    I18N_NOOP( "Tasks" )    },
  { KOLAB_FOLDER_TYPE_JOURNAL, I18N_NOOP( "Journal" )  },
  { KOLAB_FOLDER_TYPE_NOTE,    I18N_NOOP( "Notes" )    },
  { KOLAB_FOLDER_TYPE_CONFIGURATION, I18N_NOOP( "Configuration" )    },
  { KOLAB_FOLDER_TYPE_FREEBUSY,    I18N_NOOP( "Freebusy" ) },
  { KOLAB_FOLDER_TYPE_FILE,    I18N_NOOP( "Files" ) }

So "Notes" is what it should be looking for. This is obviously more involved (going through all folders, checking when new folders appear or a folder changes metadata ..) but would be absolutely awesome to have.

**Comment by konradrenner** [comment]
I have already implemented the scanning logic for "not root folders". Also the default in the account creation dialog is "Notes" for the root folder (so you don't have to specify it, if you use a standard Kolab installation). So if you create a folder (notebook) under a root folder on the web UI, this new notebook should be synced to your Android device, if not, it is a bug of the app ;-).

But the idea behind the configureable root folder is: One can have multiple root folders for one Kolab account. There could be e.g. a private notes folder, a business notes folder, etc. Each can have different sync intervalls and maybe, the business notes folder should just be synced with the smartphone of the company, but not with the private tablet. And with that in mind, address can not replace the account name ;-).

@aseigo can you please test if the notebook creation sync from the server works for you? If it does, I think I can close this issue?

**Comment by konradrenner** [comment]
I was able to reproduce the problem, i looks very strange... I will solve it with Issue #51
