### ISSUE TITLE
[Feature Request] RTL support

### ISSUE THREAD

**Issue by HassanHeydariNasab** [konradrenner/kolabnotes-android#50]
please add support for RTL languages .

**Comment by HassanHeydariNasab** [comment]
RTL is working well on summary section (title of note ) but doesn't work for body of note .

**Comment by konradrenner** [comment]
kolabnotes-android is using this project: https://github.com/wasabeef/richeditor-android for the Richtext-Editor. If this project supports RTL languages, kolabnotes-android will also support them.
Please file a issue there.
