### ISSUE TITLE
shared notes from other users

### ISSUE THREAD

**Issue by tjensch** [konradrenner/kolabnotes-android#58]
So far, I wasnt able to add shared notes, owned by other users. Is this a configuration error on my end or is not implemented yet?

**Comment by konradrenner** [comment]
Do you want to share notes with users on your local Android device, or have you notes shared on your Kolab server with other users?

**Comment by tjensch** [comment]
ah - sorry: another user on a kolab server has shared their notes with me. With roundcube I can work with them. With kolabnotes these are not available (I can select my own notes, though).

**Comment by konradrenner** [comment]
Please correct me if I am wrong, or confirm if it is the case ;-) : 
You have a notebook which you have shared with an other user. You have created notes in this notebook and the other user has also created note in this notebook. You can view and edit the notes from the other user on the Web UI, but not with kolabnotes-android. With kolabnotes-android you can just view and edit your own notes.

**Comment by tjensch** [comment]
yes, that description is correct: one minor difference in my specific setup is that the other user created the notebook, but I guess it should work either way preferably.

**Comment by konradrenner** [comment]
OK, I think this is an important feature. I will create a testserver with that use case.

I have 3 questions left: Do you see notes with classification private from the other user? Do you see notes with classification confidential from the other user? Does the other user see notes which you created with classification private or confidential?

**Comment by tjensch** [comment]
What do you mean with the classification of notes? I couldnt find any options in roundcube to set notes to private or confidential. So far, I thought, this is a calendar feature only. Beside that I guess, I wouldnt share confidential notes anyway (e.g. put them in another notebook).

**Comment by danielegobbetti** [comment]
I confirm the issue of not being able to see shared notebooks on the android app. Could it just be a folder subscription problem? The shared notebooks are "outside" of the /Notes folder.

**Comment by konradrenner** [comment]
@danielegobbetti if your shared notebooks are "outside" the /Notes folder, please create a new account where you configure the "root folder" property of the account creation dialog to point to the shared notebook.

Does it work for you? Do you see the shared notebooks/notes?

**Comment by danielegobbetti** [comment]
@konradrenner unfortunately if I add "Other Users" as root folder (which, according to the roundcube UI is the root folder for shared notebooks) I get a crash in the App.

**Comment by konradrenner** [comment]
@danielegobetti can you provide me some error trace? Have you tried to create an account with a shared notebook as the root folder?

**Comment by konradrenner** [comment]
By the way: thank you for your informations ;+)

**Comment by danielegobbetti** [comment]
@konradrenner unfortunately nothing beside:

```
D/SyncManager( 1148): failed sync operation shared u0 (kore.kolabnotes), kore.kolabnotes, SERVER, currentRunTime 89216971, reason: AutoSync, SyncResult: syncAlreadyInProgress: true stats []
```

is visible in the logcat output.

Buth there is a notification that gets shown and it tells:
java.lang.IllegalStateException: korex.mail.FolderNotFoundException: Other users not found

The Other users folder is definitely there, but I cannot subscribe to it from (i.e.) Thunderbird, hence it is maybe a "special" folder...

**Comment by konradrenner** [comment]
Thank you very much for the informations! I will ask the Kolab developers via mailinglist how to handle shared folders in an IMAP client app (kolabnotes-android also uses IMAP for sync)

**Comment by danielegobbetti** [comment]
Hi again,

I just tried adding the full path to the shared folder and it works!
The problem is that every user that shares a folder with you needs a separate account setup in the app, as the shared folder is like
/Other Users/user 1/share
And only the bottom level is a real folder accepted by the app.

The same is true for global shared folders, hence here a new account is needed for each share.

It would be really cool if the topmost "virtual" folders could be used instead.

**Comment by konradrenner** [comment]
What do you mean with "It would be really cool if the topmost "virtual" folders could be used instead."? 
Can you provide an example?

So the really great point is, that syncing of shared folders is already possible, but it is not user friendly.
Hmmm, I am not sure how to make it user friendly :-/ . @danielegobbetti  Do you have any idea?

**Comment by danielegobbetti** [comment]
> What do you mean with "It would be really cool if the topmost "virtual"
> folders could be used instead."? 
> Can you provide an example?
> 
> So the really great point is, that syncing of shared folders is already
> possible, but it is not user friendly.
> Hmmm, I am not sure how to make it user friendly :-/ . @danielegobbetti
> Do you have any idea?

Yes the two questions are related :)

It would be cool if one could add an account apecifying as folder:
/Other Users (for single shares by other users)
Or
/Shared Folders (for server global shares)

And the app could add several notebooks (each per every descendant notes folder found).

If this logic was present in the app, then the app could subscribe to these folder trees automatically when adding a kolab server.

Do you think something like this is possible? I believe the mechanism used is the "standard" imap subscription.

**Comment by konradrenner** [comment]
Impossible is nothing ;-)

@danielegobbetti what do you think about the following idea:
In the extended options area could be a checkbox "include shared notebooks", which is set checked per default. So shared notebooks are displayed and synced in the app by default, but if one doesn't want to sync shared folders for an account, he just has to uncheck the checkbox.

Do you think that it could be necessary, to select from which other users notebooks should be synced?

**Comment by danielegobbetti** [comment]
@konradrenner that would certainly be a super solution! :)

As the user is not in control of when other users share a notebook with him, I believe the best strategy would be to check the whole "/Other Users/" folder tree each time a synchronization is initiated.

**Comment by konradrenner** [comment]
Great that you like it! The automatic scan is also part of "the plan" ;-)

I just have to create a test environment, I hope I get my virtualbox Kolab installation running :-/

**Comment by danielegobbetti** [comment]
I can create an account on my server if you want, and add you to a global + user share. Just let me know!

**Comment by konradrenner** [comment]
That would be awesome! 

Can you send me the credentials and server informations, when you have created the testuser?

**Comment by danielegobbetti** [comment]
I managed to trigger a with the global share. I have the path configured correctly and the notes created on server are fetched, however notes created on the phone are never synced to the server. This is what I can see in logcat:

```
W/Binder  (22721): Caught a RuntimeException from the binder stub implementation.
W/Binder  (22721): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
W/Binder  (22721):  at org.kore.kolabnotes.android.fragment.OverviewFragment.refreshFinished(OverviewFragment.java:527)
W/Binder  (22721):  at org.kore.kolabnotes.android.MainActivity.onStatusChanged(MainActivity.java:109)
W/Binder  (22721):  at android.content.ContentResolver$1.onStatusChanged(ContentResolver.java:2342)
W/Binder  (22721):  at android.content.ISyncStatusObserver$Stub.onTransact(ISyncStatusObserver.java:53)
W/Binder  (22721):  at android.os.Binder.execTransact(Binder.java:446)
W/Binder  (22721): Caught a RuntimeException from the binder stub implementation.
W/Binder  (22721): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
W/Binder  (22721):  at org.kore.kolabnotes.android.fragment.OverviewFragment.refreshFinished(OverviewFragment.java:527)
W/Binder  (22721):  at org.kore.kolabnotes.android.MainActivity.onStatusChanged(MainActivity.java:109)
W/Binder  (22721):  at android.content.ContentResolver$1.onStatusChanged(ContentResolver.java:2342)
W/Binder  (22721):  at android.content.ISyncStatusObserver$Stub.onTransact(ISyncStatusObserver.java:53)
W/Binder  (22721):  at android.os.Binder.execTransact(Binder.java:446)
W/Binder  (31110): Caught a RuntimeException from the binder stub implementation.
```

I find it funny that the notes are fetched, despite the error.

**Comment by konradrenner** [comment]
The latest push contains the changes as discussed here. Please pull the latestet master and let me know if everything works fine. Thanks!

**Comment by danielegobbetti** [comment]
Latest master works well for me! Thanks for implementing this feature!

**Comment by konradrenner** [comment]
Great! I will soon release a new version.
