### ISSUE TITLE
Please support android 4.2

### ISSUE THREAD

**Issue by msjoberg** [konradrenner/kolabnotes-android#60]
The [Fairphone 1 is stuck on Android 4.2.2](https://www.fairphone.com/2014/12/09/our-approach-to-software-and-ongoing-support-for-the-first-fairphones/), and I would very much like to use this app :-)

**Comment by konradrenner** [comment]
One thing which I cannot support is inserting images into a note for versions lower than 4.4 (I am using the storage access framework which is available starting with 4.4). If you can live without that feature I will try to make it compatible. Is it OK?

**Comment by msjoberg** [comment]
That sounds like a reasonable compromise. I realise supporting older versions is always a hassle. I mostly need text notes anyway. Thanks!

**Comment by konradrenner** [comment]
OK, it should be possible to support everything except inline images. I hope that I find some time next week ;-)

**Comment by msjoberg** [comment]
Great! And many thanks!!

**Comment by konradrenner** [comment]
I will publish a new version on Google Play today. I don't know when the F-Droid guys are building the app.

**Comment by msjoberg** [comment]
Great! Many thanks!! :-)

I'm actually using F-Droid, so I'll be waiting for them to update then.
