### ISSUE TITLE
Lots of data is used even if no changes occur (at least on an IMAP server)

### ISSUE THREAD

**Issue by dicer** [konradrenner/kolabnotes-android#62]
I had been testing the kolabnotes with 3 or 4 notes and with one image. This was a couple of weeks ago and I haven't made any changes to any of the notes.
I had the sync interval set to a pretty low value. Something like every 30 minutes. Maybe 10. I used over 500MB of my data just this month. Sorry, don't remember the exact sync interval, because I was roaming abroad and had to uninstall the app quickly.

Anyhow: Could it be that the complete XML message gets downloaded each time? I can't imagine this could just be logins and basic IMAP calls. Could this be a server issue (dovecot on debian weezy)?

**Comment by konradrenner** [comment]
already added changes to kolabnotes-java (the sync library) to solve this problem. XML will just be loaded completely, if the note is newer or changed after the last sync date.
Need to adopt the sync call in the app now

**Comment by konradrenner** [comment]
Should be fixed with next release, which is on the way ;-)
