### ISSUE TITLE
There are a few ideas worth-whether to release?

### ISSUE THREAD

**Issue by proninyaroslav** [konradrenner/kolabnotes-android#63]
Hello. I am currently working on reworking the application. At the moment, there are a few ideas.
Already done:
1) Now the color of the text of the note is changed depending on the background

![screenshot_2015-08-24-19-37-56](https://cloud.githubusercontent.com/assets/7840559/9446105/70262fac-4a98-11e5-94d4-de2708aae1c0.png)

2) Indent in text editor

Before: 
![screenshot_2015-08-21-19-03-52](https://cloud.githubusercontent.com/assets/7840559/9446290/783727ae-4a99-11e5-968d-a09f43b51968.png)

After: 
![screenshot_2015-08-24-19-47-44](https://cloud.githubusercontent.com/assets/7840559/9446294/862ea292-4a99-11e5-926d-1dcea8488722.png)

Planned:
1) Icons in the Material Style

![screenshot_2015-08-24-19-55-22](https://cloud.githubusercontent.com/assets/7840559/9446393/2cb83fb0-4a9a-11e5-8913-f9d04e130f5b.png)

2) Multiple choice for remove notes (or swipe gesture)
3) The ability to remove the tag (currently only in note)
4) Fixing merging of color in the toolbar (for light colors)

![screenshot_2015-08-24-20-01-58](https://cloud.githubusercontent.com/assets/7840559/9446615/4c2ac2c2-4a9b-11e5-96e1-cbb302145f2a.png)

5) Saving activity between transitions from portrait to landscape mode (for dialog boxes and text editor)

I want to hear constructive criticism and suggestions, if any.

Yaroslav Pronin.

**Comment by konradrenner** [comment]
Really great! I have added you to the collaborators of the project, so you can grab any issue and work on it.

For Point 2 and 3 exist already the issue #28 but nobody is currently working on it, so it would be really great if you can take that one ;-).

Also the other points are sounding good, so send me merge request ;-)

**Comment by konradrenner** [comment]
So the answere of your question is: this ideas are really worth for release, as soon as possible :-)

**Comment by proninyaroslav** [comment]
Ok, maybe today I can send 2-3 commits, as soon as completed yet icons and removing tags.

**Comment by proninyaroslav** [comment]
Hello. Today has made the removal of the tag. But there is one thing: remove along with a note (that have this tag) or only delete the tag? At the moment I made the removal of the tag, along with a notes. Removing only tag more difficult, since after removing the tag will still be displayed on the note.

**Comment by konradrenner** [comment]
Do you mean remove of a tag or remove tags in a note?
Removing tags can cause many problem, especially how they are implemented at the moment (more details please have a look at issue #53 ).
The biggest problem IMO is, if you delete a tag, this tag will be deleted on the server too. But tags are "global objects", so if you have tagged e.g. a mail with this tag, this will also be removed. I think deletion of tags should not be possible with the app, it should just be possible on the server.

**Comment by konradrenner** [comment]
But first of all issue #53 should be solved, then we can discuss if removing tags is a good idea ;-).

Of course remove a tag from a note should always be possible and it would be cool, if one can alter tags from many notes at the same time (batch update as described in issue #28 ).

**Comment by proninyaroslav** [comment]
Ok, I then better start working on the multi-selection.

**Comment by konradrenner** [comment]
I think this one can be closed. I assign the multi-selection issue to you, I hope this is OK ;-)
