### ISSUE TITLE
Allow selecting Account/Notebook from Note Creation dialog

### ISSUE THREAD

**Issue by greve** [konradrenner/kolabnotes-android#65]
Typical use case: I come across something interesting while browing the web on the phone and want to take a note to look into it later. So I share it with Kolab Notes via the Android Share function.

This goes straight into the Note Creation dialog (good).

But it also means I am now stuck in whatever account I had last selected when editing notes (private vs work) and following Murphy's Law, it's always the wrong one (not good).

Not to mention that I'd usually like to drop all of this into a special scratchpad kind of notebook to keep the rest clean.

Hence: Please allow selection of Account & Notebook within account from within the Note Creation dialog.

**Comment by konradrenner** [comment]
Jep, that is a really good point. I am using just one account so, I didn't have this problem until now

**Comment by konradrenner** [comment]
I pushed the changes to solve this issue today @greve : please let me know if it is now OK for
