### ISSUE TITLE
Change text color of icon bar when a note has a light color

### ISSUE THREAD

**Issue by lhitc** [konradrenner/kolabnotes-android#66]
When editing a note, the icon bar is displayed in the note's color.
A light background color like yellow renders the bar almost unreadable (white text/icons on yellow).
It would be great to change the text color according to the note's background color just as it is in the list view.

**Comment by konradrenner** [comment]
refactored the code, so that the decision if the text should be displayed in a light or dark color is the same as in notes overview.
Now I have to change behaviour of toolbar

**Comment by konradrenner** [comment]
fixed in next version of the app

**Comment by lhitc** [comment]
Text color changes now, but the icons remain white

**Comment by konradrenner** [comment]
Found the Problem, will be fixed in next version
