### ISSUE TITLE
Default color per category

### ISSUE THREAD

**Issue by lhitc** [konradrenner/kolabnotes-android#67]
It would be nice to have a color associated with every category so that the note gets the category's color by default.

**Comment by konradrenner** [comment]
The color should also be synced of course

**Comment by konradrenner** [comment]
there must also be an extension being done in the kolabnotes-java project (handles the sync)

**Comment by konradrenner** [comment]
I have thought a while now on this task and I don't think automatically assigning a color to a note is a good idea. 

But at the moment the app has no ability to assign colors for tags, so I think it will be better that it is possible to assign colors to tags/categories and the assigned colors are visible in the UI (especially when a note has more than 1 tag).

I have already checked if syncing of colors for tags is possible and it definitely is :-).

Would that be OK for you?

**Comment by lhitc** [comment]
Makes sense, especially considering the better consistency when using multiple tags/categories on a note.

**Comment by konradrenner** [comment]
I implement this feature in the course of issue #53 . Because it needs a partial rewrite of the tag handling of the app.
