### ISSUE TITLE
Define a color set

### ISSUE THREAD

**Issue by lhitc** [konradrenner/kolabnotes-android#68]
The coloring of notes is somewhat random as the user can't choose from a default selection but has to use the full palette for every note.
It would be great if there was a list of previously used colors to choose from (in addition to adding a new one)

**Comment by konradrenner** [comment]
@lhitc do you mean something like this (the list pre defined colors are scrollable of course):
![overview4](https://cloud.githubusercontent.com/assets/1727807/10395438/3e9a51ba-6e9d-11e5-95c3-1c2c42324b60.png)

**Comment by konradrenner** [comment]
fixed in next version
