### ISSUE TITLE
Meta information takes much space

### ISSUE THREAD

**Issue by lhitc** [konradrenner/kolabnotes-android#69]
In the list view, meta information (category, classification and the two timestamps) take up much space.
I would prefer to have a way to switch them off in list view (make every of these items configurable)

**Comment by konradrenner** [comment]
As Addition to this issue I think the metainformations should be possible to display in detail activity (Dialog, or a side bar which can be swiped in, or some way else)

**Comment by konradrenner** [comment]
will be implemented in next version
