### ISSUE TITLE
Make the sync interval configurable

### ISSUE THREAD

**Issue by lhitc** [konradrenner/kolabnotes-android#70]
I mentioned this in an earlier issue, but afair that was not the main point there, so:

Please give the user an option to configure the sync interval.
I personally switch between phone and tablet (and PC, but that's a different issue, as we know) multiple times a day so I need syncing to be done in rather short intervals.

**Comment by konradrenner** [comment]
When you create an account it is already possible to specify the sync Intervall.

Do you want to change the Intervall for an existing account (for this one already exists an issue) or do you want to have the ability to specify a value lower than an hour?

Also it is possible to trigger the sync via "swipe refresh".  So if you want to sync outside the configured Intervall you can do this already.

**Comment by lhitc** [comment]
Oh, I didn't realize the configuration option (didn't create an account for some time).
Basically I'd like to have both options you mentioned, but swiping is an acceptable workaround if sync is needed "instantly".
Should have searched the issues more intense ;-)

**Comment by konradrenner** [comment]
Next version will also get ability to change Intervall and choose other intervalls (days, minutes, hours)
