### ISSUE TITLE
Provide STARTTLS Support 

### ISSUE THREAD

**Issue by PulsarFX** [konradrenner/kolabnotes-android#76]
![screenshot_2015-10-30-08-40-28 01](https://cloud.githubusercontent.com/assets/4960210/10840696/1e048650-7ee2-11e5-95a7-1a87ad84fc1b.png)

**Comment by PulsarFX** [comment]
Sorry for empty Ticket description .... 

I get a handshake failed exception

**Comment by konradrenner** [comment]
@maulwuff can you please test the apk and tell me if it works for you: https://www.dropbox.com/s/llx6vd5hrptt387/app-release.apk?dl=0

**Comment by PulsarFX** [comment]
I downloaded the apk, deleted all accounts, the app data and readded my Account. It gives me the same error. 
Although, I chose IMAP, I don't know if it works with dovecot. Just learned, that kolab has very special requirements which my Server currently doesn't meet. 

Am 31. Oktober 2015 08:48:25 MEZ, schrieb Konrad Renner notifications@github.com:

**Comment by konradrenner** [comment]
Please select "Kolab Server" in the account creation wizard, it is important that the "kolab extensions" option from the extended options is active. Also: are you sure that the IMAP port is 993?

**Comment by konradrenner** [comment]
Hi, does it work with the new version of the app?

**Comment by PulsarFX** [comment]
I think it worked after readding the account. As I use StartTLS I have to use Port 143. 

Now I get refresh failed. But as stated above, I use dovecot, not cyrus - maybe it's because of that.
When expanding the notification, I see that this is actually a handshake failed, too.

**Comment by konradrenner** [comment]
Hmm, I cannot reproduce it. Maybe you can provide me a test account on your server?

**Comment by PulsarFX** [comment]
you think it should work with dovecot?

**Comment by konradrenner** [comment]
It should, but I don't have a server with that constellation. So if you could provide me a test account on your server, I can debug the app und check, why it don't work.

My goal is, the help every user of my app, which reports an issue ;-)

**Comment by PulsarFX** [comment]
Are you on g+? Github seems to have no way for pm

Am 15. November 2015 08:13:15 MEZ, schrieb Konrad Renner notifications@github.com:

**Comment by konradrenner** [comment]
https://plus.google.com/114310231739396530319/posts

**Comment by PulsarFX** [comment]
Solltest irgendwas per Benachrichtigung bekommen haben. 

Am 15. November 2015 09:53:44 MEZ, schrieb Konrad Renner notifications@github.com:

**Comment by konradrenner** [comment]
Leider nicht. Schick mir bitte eine Mail an koni.renner@gmail.com

**Comment by konradrenner** [comment]
Ich konnte das Problem nun nachstellen und arbeite an einer Lösung.

**Comment by konradrenner** [comment]
@maulwuff I have done some testing. First of all: thank you for the test account! I was able to connect to the account now, but I cannot sync, because there is no "Notes" folder on the server and I cannot create one because I don't know how to access the web UI.

So can you please test the attached apk if it works for you?

https://www.dropbox.com/s/llx6vd5hrptt387/app-release.apk?dl=0

**Comment by PulsarFX** [comment]
Works ;-)
So to use with dovecot settings are as follows :
- IMAP Server + correct connection settings 
- No shared notes
- No kolab Extensions 
- Existing Notes folder (or other exclusive folder) 

After sync i was able to see the note in k9

**Comment by konradrenner** [comment]
Great to hear! Thank you for providing me the test account, I don't need it now anymore ;-).
I will publish a new version of the app today or tomorrow!
