### ISSUE TITLE
Adding text to newly created notes

### ISSUE THREAD

**Issue by danielegobbetti** [konradrenner/kolabnotes-android#77]
After entering the title, one has to tap in the top-right angle of the note body field, otherwise the note cannot be entered (sony xperia Z3C, android 5.1.1)

**Comment by konradrenner** [comment]
I will switch to the latest Version of the Richtext view from https://github.com/wasabeef/richeditor-android maybe it solves this issue

**Comment by danielegobbetti** [comment]
I changed the background color of the rich text editor in the fragment_detail.xml file, and noticed that its height is only a couple of pixel, so perhaps the layout could be arranged differently (I made some tests but they were unsuccessful: I don't understand fragments :) )

**Comment by konradrenner** [comment]
Yep, I know. But I configured the view that it should fill the space... Maybe with the new version it is fixed

**Comment by konradrenner** [comment]
No change :-(, but I was able to make the initial text area bigger. I think this issue should be handled from this project (which I use for the richtext editor): https://github.com/wasabeef/richeditor-android
