### ISSUE TITLE
Classification: Public

### ISSUE THREAD

**Issue by grote** [konradrenner/kolabnotes-android#85]
As part of "Characteristics" the app is showing "Classification: Public" below the notes. [In Kolab, the public attribute of the specification is not used](https://issues.kolab.org/show_bug.cgi?id=2956), because Notes are not public, they can only be shared with others. If this is what is meant by public, I suggest to remove the classification to prevent confusion.

**Comment by konradrenner** [comment]
Ok, I didn't know that. I will hide this property in the GUI

**Comment by konradrenner** [comment]
Should be fixed with 1.1.0
