### ISSUE TITLE
Improve Change Notifications

### ISSUE THREAD

**Issue by grote** [konradrenner/kolabnotes-android#86]
Hi,

I would like to make some suggestions to improve working with shared notebooks.

**Change Notifications**
When a note was changed after an account sync, notifications are shown for each changed note. IMHO, these notifications should be opt-in or at least provide an option for turning them off.
If they are shown, a click on the notification should open the note the notification was for. Currently, nothing happens when clicking the note.

Related issues are:
- **Sync changes immediately** #87 
- **Conflict Handling** #88

**Comment by konradrenner** [comment]
I like the suggestions, but I think each of them is worth its own issue ;-)

**Comment by grote** [comment]
Alright, I split out the other two issues and updated this one.

**Comment by konradrenner** [comment]
Already worked on it, will be fixed with christmas version ;-)

**Comment by grote** [comment]
Awesome, looking forward to it! :)

**Comment by konradrenner** [comment]
done with version 1.20
