### ISSUE TITLE
Modification of tags

### ISSUE THREAD

**Issue by konradrenner** [konradrenner/kolabnotes-android#97]
Deletion or changing the name of a tag is a little bit tricky, because if you sync the notes and tags with a Kolab server, other groupware objects are also affected with tag changes (eg if you delete the "Work" tag in the app, every E-Mail which was marked with this tag will also loose this tag, on the server and on other Clients).

So there must be a warning for the user that changing/deleting a tag will maybe affect other groupware objects.

At the moment it is just possible to change the color of a selected tag, I think the best way to implement tag changing/deletion would be to create a new section in the apps preferences/settings for tags (the changing of a tag color should also be there in the future). There it should be possible to select a tag via a ListView and display the details of a selected tag in a separate fragment where you can edit (name and color) and delete the tag or create a new one.

The action menus of the overview fragment must be removed after the new preferences section is created and fully functional because all the functions are available in the new preferences section then.

**Comment by proninyaroslav** [comment]
I do it in the near future.

**Comment by ninjahoahong** [comment]
This feature is much needed because when a tag is accidentally created and will not be used then it floods the navigation drawer.

**Comment by konradrenner** [comment]
thx @proninyaroslav for the pull request, I have merged it now. But there are some problems open, right now:
1. the join between tags and notes (in the NoteTagRepository) is done with the tag name at the moment, so if one renames a tag, a note is not tagged with it anymore. It would be correct if the tag is on the note, but renamed (for the old logic the behavior was no problem, because renaming was not possible ;-) )
2. A deletion of a tag will not getting synced, I have to implement it in the sync lib
3. Some translations are not correct

I will fix issues 2 + 3, do you have some time to look on issue 1?

**Comment by konradrenner** [comment]
One addition to point 1:
This one is really tricky because if there is just an change of the column which is used for the join, existing relations will break (because in the notetag.tag_id field is the name of the tag and not its UID).
So there must be an migration at the first startup of the app, after an app update, or something like an OR clause, which will be not good for performance, or something else which doesn't break existing data, but supports the new renaming feature...

**Comment by proninyaroslav** [comment]
I thought about 1 point yesterday and noticed that you are using tag name, not his UID. This primordial error, alas. So far, I see two options: either to do notes migration tool, either if you change the tag, update all notes (but with sync with the server this is unlikely).
I would like to consult with you how best to proceed.

**Comment by konradrenner** [comment]
I think the best way will be to check at app start (onCreate of OverviewActivity) a shared preference "notetag_migration" or something like this. If the preference has the value true, everything is OK. If not, the notestag.tagid column has to be updated with the corresponding uid from the newtag table, which match the tag name. And the join must use the column uid of the newtag table.

I know it was a bad design desicion :-/, but I didn't know the storage format of tags that good when I started developing the app.

**Comment by proninyaroslav** [comment]
Ok, I will try to do in the coming days.

**Comment by konradrenner** [comment]
Great, thank you very much!!!

**Comment by proninyaroslav** [comment]
@konradrenner,
I looked at the code, and situation turned complex: it is necessary to change a lot of code (show, change, migration, add). I have no time and the knowledge internal structure of the program that you have.
I propose an option: share the responsibility in this task and each will do their part.

**Comment by konradrenner** [comment]
ok thanks, I will look at it on my own. I hope to find some time at the weekend.

**Comment by konradrenner** [comment]
maybe it is easier, if the tag_id field in the notetags table is also updated, everything should be fine. I will test it... I have already added the deletion sync capability to the sync library

**Comment by konradrenner** [comment]
that worked :-), Issue will be solved with next version

**Comment by konradrenner** [comment]
@proninyaroslav thanks for your help!!!
