### ISSUE TITLE
Creating a wiki page for contributors

### ISSUE THREAD

**Issue by ninjahoahong** [konradrenner/kolabnotes-android#99]
How do you think on creating a simple wiki page with the instruction on how should anyone would contribute to the project? For example, any notice or difficulty the developers might face when implementing a new features or modifying the current features.

**Comment by konradrenner** [comment]
Good point, I will create a wikipage for contributors

**Comment by ninjahoahong** [comment]
@konradrenner thank you.

**Comment by konradrenner** [comment]
wiki page is created: https://github.com/konradrenner/kolabnotes-android/wiki/Infos-for--contributors
